#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("dummy_tmr_out_i", 1, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("dummy_tmr_out_o", 1, hls_out, 0, "ap_none", "out_data", 1),
	Port_Property("rs_i", 1, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("rs_o", 1, hls_out, 1, "ap_none", "out_data", 1),
	Port_Property("en_i", 1, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("en_o", 1, hls_out, 2, "ap_none", "out_data", 1),
	Port_Property("data_i", 4, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("data_o", 4, hls_out, 3, "ap_none", "out_data", 1),
	Port_Property("ind", 1, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("mem_addr_i", 5, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("mem_addr_o", 5, hls_out, 5, "ap_none", "out_data", 1),
	Port_Property("mem_din", 8, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("mem_req_i", 1, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("mem_req_o", 1, hls_out, 7, "ap_none", "out_data", 1),
	Port_Property("mem_ack", 1, hls_in, 8, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "lcddrv";
