#pragma line 1 "motor_ctrl.c" ::: 0
#pragma line 1 "motor_ctrl.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 147 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 283 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 64
#pragma line 421 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 191
#pragma line 7 "<command line>" 2 ::: 193
#pragma line 1 "<built-in>" 2 ::: 194
#pragma line 1 "motor_ctrl.c" 2 ::: 195
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" 1 ::: 235
#pragma line 62 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" ::: 288
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 289
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 299
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 310
#pragma line 18 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 316
#pragma line 62 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 330
#pragma line 10 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 337
#pragma line 32 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 341
#pragma line 147 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 344
#pragma line 225 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 348
#pragma line 247 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 350
#pragma line 277 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 352
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 353
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 367
#pragma line 674 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 373
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 374
#pragma line 674 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 375
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 377
#pragma line 675 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 378
#pragma line 13 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 379
#pragma line 46 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 399
#pragma line 102 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 401
#pragma line 277 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 403
#pragma line 316 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 407
#pragma line 370 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 413
#pragma line 380 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 415
#pragma line 392 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 417
#pragma line 405 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 419
#pragma line 418 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 421
#pragma line 428 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 423
#pragma line 456 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 434
#pragma line 518 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 454
#pragma line 605 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 468
#pragma line 9 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 532
#pragma line 36 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 3 ::: 533
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 1 3 ::: 674
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 684
#pragma line 9 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 2 3 ::: 690
#pragma line 175 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 691
#pragma line 63 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" 2 ::: 692
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 693
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 703
#pragma line 9 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 709
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 712
#pragma line 11 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 720
#pragma line 26 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 724
#pragma line 84 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 736
#pragma line 120 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 755
#pragma line 157 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 757
#pragma line 312 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 903
#pragma line 330 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 911
#pragma line 373 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 947
#pragma line 417 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 982
#pragma line 475 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1012
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 1048
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 1058
#pragma line 9 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 1064
#pragma line 509 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1065
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 1068
#pragma line 511 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1076
#pragma line 64 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" 2 ::: 1077
#pragma line 77 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" ::: 1078
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 1079
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 1 ::: 1137
#pragma line 97 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" ::: 1191
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 1192
#pragma line 98 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 2231
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 2232
#pragma line 99 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 3259
#pragma line 108 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" ::: 3260
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 3261
#pragma line 109 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 4300
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 4301
#pragma line 110 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 5328
#pragma line 131 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" ::: 5329
#pragma line 147 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" ::: 5332
#pragma line 58 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5334
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" 1 ::: 5335
#pragma line 98 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5388
#pragma line 108 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5390
#pragma line 129 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5392
#pragma line 143 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5397
#pragma line 156 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5400
#pragma line 192 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5402
#pragma line 358 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5404
#pragma line 59 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5406
#pragma line 85 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" ::: 5407
#pragma line 114 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" ::: 5409
#pragma line 78 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" 2 ::: 5411
#pragma line 88 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" ::: 5412
#pragma line 39 "motor_ctrl.c" 2 ::: 5414
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_utils.h" 1 ::: 5416
#pragma line 73 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_utils.h" ::: 5469
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 5470
#pragma line 74 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_utils.h" 2 ::: 5605
#pragma line 40 "motor_ctrl.c" 2 ::: 5612
