// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "bno055_uart_uart_receive_byte.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic bno055_uart_uart_receive_byte::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic bno055_uart_uart_receive_byte::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> bno055_uart_uart_receive_byte::ap_ST_st1_fsm_0 = "1";
const sc_lv<12> bno055_uart_uart_receive_byte::ap_ST_st2_fsm_1 = "10";
const sc_lv<12> bno055_uart_uart_receive_byte::ap_ST_st3_fsm_2 = "100";
const sc_lv<12> bno055_uart_uart_receive_byte::ap_ST_st4_fsm_3 = "1000";
const sc_lv<12> bno055_uart_uart_receive_byte::ap_ST_st5_fsm_4 = "10000";
const sc_lv<12> bno055_uart_uart_receive_byte::ap_ST_st6_fsm_5 = "100000";
const sc_lv<12> bno055_uart_uart_receive_byte::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<12> bno055_uart_uart_receive_byte::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<12> bno055_uart_uart_receive_byte::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<12> bno055_uart_uart_receive_byte::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<12> bno055_uart_uart_receive_byte::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<12> bno055_uart_uart_receive_byte::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<32> bno055_uart_uart_receive_byte::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> bno055_uart_uart_receive_byte::ap_const_lv1_1 = "1";
const sc_lv<32> bno055_uart_uart_receive_byte::ap_const_lv32_2 = "10";
const sc_lv<1> bno055_uart_uart_receive_byte::ap_const_lv1_0 = "0";
const sc_lv<32> bno055_uart_uart_receive_byte::ap_const_lv32_7 = "111";
const sc_lv<32> bno055_uart_uart_receive_byte::ap_const_lv32_4 = "100";
const sc_lv<24> bno055_uart_uart_receive_byte::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<32> bno055_uart_uart_receive_byte::ap_const_lv32_1 = "1";
const sc_lv<8> bno055_uart_uart_receive_byte::ap_const_lv8_0 = "00000000";
const sc_lv<32> bno055_uart_uart_receive_byte::ap_const_lv32_6 = "110";
const sc_lv<32> bno055_uart_uart_receive_byte::ap_const_lv32_B = "1011";
const sc_lv<4> bno055_uart_uart_receive_byte::ap_const_lv4_0 = "0000";
const sc_lv<32> bno055_uart_uart_receive_byte::ap_const_lv32_3 = "11";
const sc_lv<32> bno055_uart_uart_receive_byte::ap_const_lv32_5 = "101";
const sc_lv<32> bno055_uart_uart_receive_byte::ap_const_lv32_8 = "1000";
const sc_lv<32> bno055_uart_uart_receive_byte::ap_const_lv32_A = "1010";
const sc_lv<28> bno055_uart_uart_receive_byte::ap_const_lv28_D9 = "11011001";
const sc_lv<28> bno055_uart_uart_receive_byte::ap_const_lv28_28B = "1010001011";
const sc_lv<28> bno055_uart_uart_receive_byte::ap_const_lv28_1B2 = "110110010";
const sc_lv<32> bno055_uart_uart_receive_byte::ap_const_lv32_9 = "1001";
const sc_lv<24> bno055_uart_uart_receive_byte::ap_const_lv24_989680 = "100110001001011010000000";
const sc_lv<24> bno055_uart_uart_receive_byte::ap_const_lv24_1 = "1";
const sc_lv<4> bno055_uart_uart_receive_byte::ap_const_lv4_8 = "1000";
const sc_lv<4> bno055_uart_uart_receive_byte::ap_const_lv4_1 = "1";

bno055_uart_uart_receive_byte::bno055_uart_uart_receive_byte(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_bno055_uart_wait_tmr_fu_85 = new bno055_uart_wait_tmr("grp_bno055_uart_wait_tmr_fu_85");
    grp_bno055_uart_wait_tmr_fu_85->ap_clk(ap_clk);
    grp_bno055_uart_wait_tmr_fu_85->ap_rst(ap_rst);
    grp_bno055_uart_wait_tmr_fu_85->ap_start(grp_bno055_uart_wait_tmr_fu_85_ap_start);
    grp_bno055_uart_wait_tmr_fu_85->ap_done(grp_bno055_uart_wait_tmr_fu_85_ap_done);
    grp_bno055_uart_wait_tmr_fu_85->ap_idle(grp_bno055_uart_wait_tmr_fu_85_ap_idle);
    grp_bno055_uart_wait_tmr_fu_85->ap_ready(grp_bno055_uart_wait_tmr_fu_85_ap_ready);
    grp_bno055_uart_wait_tmr_fu_85->tmr(grp_bno055_uart_wait_tmr_fu_85_tmr);
    grp_bno055_uart_wait_tmr_fu_85->dummy_tmr_out_i(dummy_tmr_out_i);
    grp_bno055_uart_wait_tmr_fu_85->dummy_tmr_out_o(grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o);
    grp_bno055_uart_wait_tmr_fu_85->dummy_tmr_out_o_ap_vld(grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o_ap_vld);
    grp_bno055_uart_read_uart_rx_fu_95 = new bno055_uart_read_uart_rx("grp_bno055_uart_read_uart_rx_fu_95");
    grp_bno055_uart_read_uart_rx_fu_95->uart_rx(uart_rx);
    grp_bno055_uart_read_uart_rx_fu_95->ap_return(grp_bno055_uart_read_uart_rx_fu_95_ap_return);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( exitcond_fu_113_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( exitcond_fu_113_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( exitcond_fu_113_p2 );
    sensitive << ( data_reg_63 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_ap_sig_107);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_118);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_127);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_140);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_147);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_155);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_163);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_175);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_46);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_62);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_89);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_175 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_163 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_127 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_29 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_107 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_46 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_140 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_89 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_147 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_118 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_62 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_155 );

    SC_METHOD(thread_data_1_fu_143_p3);
    sensitive << ( tmp_4_fu_135_p3 );
    sensitive << ( tmp_6_fu_125_p4 );

    SC_METHOD(thread_dummy_tmr_out_o);
    sensitive << ( dummy_tmr_out_i );
    sensitive << ( tmp_2_reg_162 );
    sensitive << ( grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o );
    sensitive << ( grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o_ap_vld );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_dummy_tmr_out_o_ap_vld);
    sensitive << ( tmp_2_reg_162 );
    sensitive << ( grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o_ap_vld );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_exitcond_fu_113_p2);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( i_reg_74 );

    SC_METHOD(thread_grp_bno055_uart_wait_tmr_fu_85_ap_start);
    sensitive << ( ap_reg_grp_bno055_uart_wait_tmr_fu_85_ap_start );

    SC_METHOD(thread_grp_bno055_uart_wait_tmr_fu_85_tmr);
    sensitive << ( tmp_2_reg_162 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_i_2_fu_119_p2);
    sensitive << ( i_reg_74 );

    SC_METHOD(thread_timer_1_fu_107_p2);
    sensitive << ( timer_reg_52 );

    SC_METHOD(thread_tmp_1_fu_101_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( timer_reg_52 );

    SC_METHOD(thread_tmp_4_fu_135_p3);
    sensitive << ( grp_bno055_uart_read_uart_rx_fu_95_ap_return );

    SC_METHOD(thread_tmp_6_fu_125_p4);
    sensitive << ( data_reg_63 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_bno055_uart_read_uart_rx_fu_95_ap_return );
    sensitive << ( tmp_2_reg_162 );
    sensitive << ( tmp_1_fu_101_p2 );
    sensitive << ( exitcond_fu_113_p2 );
    sensitive << ( grp_bno055_uart_wait_tmr_fu_85_ap_done );

    ap_CS_fsm = "000000000001";
    ap_reg_grp_bno055_uart_wait_tmr_fu_85_ap_start = SC_LOGIC_0;
    ap_return_preg = "00000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "bno055_uart_uart_receive_byte_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, uart_rx, "(port)uart_rx");
    sc_trace(mVcdFile, dummy_tmr_out_i, "(port)dummy_tmr_out_i");
    sc_trace(mVcdFile, dummy_tmr_out_o, "(port)dummy_tmr_out_o");
    sc_trace(mVcdFile, dummy_tmr_out_o_ap_vld, "(port)dummy_tmr_out_o_ap_vld");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_29, "ap_sig_29");
    sc_trace(mVcdFile, timer_1_fu_107_p2, "timer_1_fu_107_p2");
    sc_trace(mVcdFile, timer_1_reg_157, "timer_1_reg_157");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_46, "ap_sig_46");
    sc_trace(mVcdFile, grp_bno055_uart_read_uart_rx_fu_95_ap_return, "grp_bno055_uart_read_uart_rx_fu_95_ap_return");
    sc_trace(mVcdFile, tmp_2_reg_162, "tmp_2_reg_162");
    sc_trace(mVcdFile, tmp_1_fu_101_p2, "tmp_1_fu_101_p2");
    sc_trace(mVcdFile, i_2_fu_119_p2, "i_2_fu_119_p2");
    sc_trace(mVcdFile, i_2_reg_172, "i_2_reg_172");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_62, "ap_sig_62");
    sc_trace(mVcdFile, data_1_fu_143_p3, "data_1_fu_143_p3");
    sc_trace(mVcdFile, data_1_reg_177, "data_1_reg_177");
    sc_trace(mVcdFile, exitcond_fu_113_p2, "exitcond_fu_113_p2");
    sc_trace(mVcdFile, grp_bno055_uart_wait_tmr_fu_85_ap_start, "grp_bno055_uart_wait_tmr_fu_85_ap_start");
    sc_trace(mVcdFile, grp_bno055_uart_wait_tmr_fu_85_ap_done, "grp_bno055_uart_wait_tmr_fu_85_ap_done");
    sc_trace(mVcdFile, grp_bno055_uart_wait_tmr_fu_85_ap_idle, "grp_bno055_uart_wait_tmr_fu_85_ap_idle");
    sc_trace(mVcdFile, grp_bno055_uart_wait_tmr_fu_85_ap_ready, "grp_bno055_uart_wait_tmr_fu_85_ap_ready");
    sc_trace(mVcdFile, grp_bno055_uart_wait_tmr_fu_85_tmr, "grp_bno055_uart_wait_tmr_fu_85_tmr");
    sc_trace(mVcdFile, grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o, "grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o");
    sc_trace(mVcdFile, grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o_ap_vld, "grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o_ap_vld");
    sc_trace(mVcdFile, timer_reg_52, "timer_reg_52");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_89, "ap_sig_89");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_107, "ap_sig_107");
    sc_trace(mVcdFile, data_reg_63, "data_reg_63");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_118, "ap_sig_118");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_127, "ap_sig_127");
    sc_trace(mVcdFile, i_reg_74, "i_reg_74");
    sc_trace(mVcdFile, ap_reg_grp_bno055_uart_wait_tmr_fu_85_ap_start, "ap_reg_grp_bno055_uart_wait_tmr_fu_85_ap_start");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_140, "ap_sig_140");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_147, "ap_sig_147");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_155, "ap_sig_155");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_163, "ap_sig_163");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_175, "ap_sig_175");
    sc_trace(mVcdFile, tmp_4_fu_135_p3, "tmp_4_fu_135_p3");
    sc_trace(mVcdFile, tmp_6_fu_125_p4, "tmp_6_fu_125_p4");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

bno055_uart_uart_receive_byte::~bno055_uart_uart_receive_byte() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_bno055_uart_wait_tmr_fu_85;
    delete grp_bno055_uart_read_uart_rx_fu_95;
}

void bno055_uart_uart_receive_byte::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_bno055_uart_wait_tmr_fu_85_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()))) {
            ap_reg_grp_bno055_uart_wait_tmr_fu_85_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_bno055_uart_wait_tmr_fu_85_ap_ready.read())) {
            ap_reg_grp_bno055_uart_wait_tmr_fu_85_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_113_p2.read()))) {
            ap_return_preg = data_reg_63.read();
        }
    }
    if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_bno055_uart_wait_tmr_fu_85_ap_done.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
            data_reg_63 = data_1_reg_177.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
            data_reg_63 = ap_const_lv8_0;
        }
    }
    if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_bno055_uart_wait_tmr_fu_85_ap_done.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
            i_reg_74 = i_2_reg_172.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
            i_reg_74 = ap_const_lv4_0;
        }
    }
    if ((!esl_seteq<1,1,1>(grp_bno055_uart_read_uart_rx_fu_95_ap_return.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        timer_reg_52 = ap_const_lv24_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                !(esl_seteq<1,1,1>(tmp_2_reg_162.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_bno055_uart_wait_tmr_fu_85_ap_done.read())) && 
                (!esl_seteq<1,1,1>(tmp_2_reg_162.read(), ap_const_lv1_0) || 
                 !esl_seteq<1,1,1>(grp_bno055_uart_read_uart_rx_fu_95_ap_return.read(), ap_const_lv1_0)))) {
        timer_reg_52 = timer_1_reg_157.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_113_p2.read()))) {
        data_1_reg_177 = data_1_fu_143_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        i_2_reg_172 = i_2_fu_119_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        timer_1_reg_157 = timer_1_fu_107_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && !esl_seteq<1,1,1>(tmp_1_fu_101_p2.read(), ap_const_lv1_0))) {
        tmp_2_reg_162 = grp_bno055_uart_read_uart_rx_fu_95_ap_return.read();
    }
}

void bno055_uart_uart_receive_byte::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_113_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_113_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_113_p2.read()))) {
        ap_return = data_reg_63.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void bno055_uart_uart_receive_byte::thread_ap_sig_107() {
    ap_sig_107 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void bno055_uart_uart_receive_byte::thread_ap_sig_118() {
    ap_sig_118 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void bno055_uart_uart_receive_byte::thread_ap_sig_127() {
    ap_sig_127 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void bno055_uart_uart_receive_byte::thread_ap_sig_140() {
    ap_sig_140 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void bno055_uart_uart_receive_byte::thread_ap_sig_147() {
    ap_sig_147 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void bno055_uart_uart_receive_byte::thread_ap_sig_155() {
    ap_sig_155 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void bno055_uart_uart_receive_byte::thread_ap_sig_163() {
    ap_sig_163 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void bno055_uart_uart_receive_byte::thread_ap_sig_175() {
    ap_sig_175 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void bno055_uart_uart_receive_byte::thread_ap_sig_29() {
    ap_sig_29 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void bno055_uart_uart_receive_byte::thread_ap_sig_46() {
    ap_sig_46 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void bno055_uart_uart_receive_byte::thread_ap_sig_62() {
    ap_sig_62 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void bno055_uart_uart_receive_byte::thread_ap_sig_89() {
    ap_sig_89 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void bno055_uart_uart_receive_byte::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_175.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_163.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_127.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_29.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_107.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_46.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_140.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_89.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_147.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_118.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_62.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_155.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_data_1_fu_143_p3() {
    data_1_fu_143_p3 = esl_concat<1,7>(tmp_4_fu_135_p3.read(), tmp_6_fu_125_p4.read());
}

void bno055_uart_uart_receive_byte::thread_dummy_tmr_out_o() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          esl_seteq<1,1,1>(tmp_2_reg_162.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o_ap_vld.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o_ap_vld.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o_ap_vld.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o_ap_vld.read())))) {
        dummy_tmr_out_o = grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o.read();
    } else {
        dummy_tmr_out_o = dummy_tmr_out_i.read();
    }
}

void bno055_uart_uart_receive_byte::thread_dummy_tmr_out_o_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          esl_seteq<1,1,1>(tmp_2_reg_162.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()))) {
        dummy_tmr_out_o_ap_vld = grp_bno055_uart_wait_tmr_fu_85_dummy_tmr_out_o_ap_vld.read();
    } else {
        dummy_tmr_out_o_ap_vld = ap_const_logic_0;
    }
}

void bno055_uart_uart_receive_byte::thread_exitcond_fu_113_p2() {
    exitcond_fu_113_p2 = (!i_reg_74.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_74.read() == ap_const_lv4_8);
}

void bno055_uart_uart_receive_byte::thread_grp_bno055_uart_wait_tmr_fu_85_ap_start() {
    grp_bno055_uart_wait_tmr_fu_85_ap_start = ap_reg_grp_bno055_uart_wait_tmr_fu_85_ap_start.read();
}

void bno055_uart_uart_receive_byte::thread_grp_bno055_uart_wait_tmr_fu_85_tmr() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()))) {
        grp_bno055_uart_wait_tmr_fu_85_tmr = ap_const_lv28_1B2;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        grp_bno055_uart_wait_tmr_fu_85_tmr = ap_const_lv28_28B;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                esl_seteq<1,1,1>(tmp_2_reg_162.read(), ap_const_lv1_0))) {
        grp_bno055_uart_wait_tmr_fu_85_tmr = ap_const_lv28_D9;
    } else {
        grp_bno055_uart_wait_tmr_fu_85_tmr = "XXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void bno055_uart_uart_receive_byte::thread_i_2_fu_119_p2() {
    i_2_fu_119_p2 = (!i_reg_74.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_74.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void bno055_uart_uart_receive_byte::thread_timer_1_fu_107_p2() {
    timer_1_fu_107_p2 = (!timer_reg_52.read().is_01() || !ap_const_lv24_1.is_01())? sc_lv<24>(): (sc_biguint<24>(timer_reg_52.read()) + sc_biguint<24>(ap_const_lv24_1));
}

void bno055_uart_uart_receive_byte::thread_tmp_1_fu_101_p2() {
    tmp_1_fu_101_p2 = (!timer_reg_52.read().is_01() || !ap_const_lv24_989680.is_01())? sc_lv<1>(): (sc_biguint<24>(timer_reg_52.read()) < sc_biguint<24>(ap_const_lv24_989680));
}

void bno055_uart_uart_receive_byte::thread_tmp_4_fu_135_p3() {
    tmp_4_fu_135_p3 = (!grp_bno055_uart_read_uart_rx_fu_95_ap_return.read()[0].is_01())? sc_lv<1>(): ((grp_bno055_uart_read_uart_rx_fu_95_ap_return.read()[0].to_bool())? ap_const_lv1_1: ap_const_lv1_0);
}

void bno055_uart_uart_receive_byte::thread_tmp_6_fu_125_p4() {
    tmp_6_fu_125_p4 = data_reg_63.read().range(7, 1);
}

void bno055_uart_uart_receive_byte::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(grp_bno055_uart_read_uart_rx_fu_95_ap_return.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            if ((!esl_seteq<1,1,1>(tmp_1_fu_101_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(grp_bno055_uart_read_uart_rx_fu_95_ap_return.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else if ((!esl_seteq<1,1,1>(tmp_1_fu_101_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(grp_bno055_uart_read_uart_rx_fu_95_ap_return.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            if ((!(esl_seteq<1,1,1>(tmp_2_reg_162.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_bno055_uart_wait_tmr_fu_85_ap_done.read())) && (!esl_seteq<1,1,1>(tmp_2_reg_162.read(), ap_const_lv1_0) || 
  !esl_seteq<1,1,1>(grp_bno055_uart_read_uart_rx_fu_95_ap_return.read(), ap_const_lv1_0)))) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else if ((esl_seteq<1,1,1>(tmp_2_reg_162.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(tmp_2_reg_162.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_bno055_uart_wait_tmr_fu_85_ap_done.read())) && esl_seteq<1,1,1>(grp_bno055_uart_read_uart_rx_fu_95_ap_return.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_bno055_uart_wait_tmr_fu_85_ap_done.read())) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 128 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_113_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_bno055_uart_wait_tmr_fu_85_ap_done.read())) {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            } else {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_bno055_uart_wait_tmr_fu_85_ap_done.read())) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<12>) ("XXXXXXXXXXXX");
            break;
    }
}

}

