// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module lcddrv_init_lcd (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dummy_tmr_out_i,
        dummy_tmr_out_o,
        dummy_tmr_out_o_ap_vld,
        en,
        en_ap_vld,
        rs,
        rs_ap_vld,
        data,
        data_ap_vld
);

parameter    ap_ST_st1_fsm_0 = 40'b1;
parameter    ap_ST_st2_fsm_1 = 40'b10;
parameter    ap_ST_st3_fsm_2 = 40'b100;
parameter    ap_ST_st4_fsm_3 = 40'b1000;
parameter    ap_ST_st5_fsm_4 = 40'b10000;
parameter    ap_ST_st6_fsm_5 = 40'b100000;
parameter    ap_ST_st7_fsm_6 = 40'b1000000;
parameter    ap_ST_st8_fsm_7 = 40'b10000000;
parameter    ap_ST_st9_fsm_8 = 40'b100000000;
parameter    ap_ST_st10_fsm_9 = 40'b1000000000;
parameter    ap_ST_st11_fsm_10 = 40'b10000000000;
parameter    ap_ST_st12_fsm_11 = 40'b100000000000;
parameter    ap_ST_st13_fsm_12 = 40'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 40'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 40'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 40'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 40'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 40'b100000000000000000;
parameter    ap_ST_st19_fsm_18 = 40'b1000000000000000000;
parameter    ap_ST_st20_fsm_19 = 40'b10000000000000000000;
parameter    ap_ST_st21_fsm_20 = 40'b100000000000000000000;
parameter    ap_ST_st22_fsm_21 = 40'b1000000000000000000000;
parameter    ap_ST_st23_fsm_22 = 40'b10000000000000000000000;
parameter    ap_ST_st24_fsm_23 = 40'b100000000000000000000000;
parameter    ap_ST_st25_fsm_24 = 40'b1000000000000000000000000;
parameter    ap_ST_st26_fsm_25 = 40'b10000000000000000000000000;
parameter    ap_ST_st27_fsm_26 = 40'b100000000000000000000000000;
parameter    ap_ST_st28_fsm_27 = 40'b1000000000000000000000000000;
parameter    ap_ST_st29_fsm_28 = 40'b10000000000000000000000000000;
parameter    ap_ST_st30_fsm_29 = 40'b100000000000000000000000000000;
parameter    ap_ST_st31_fsm_30 = 40'b1000000000000000000000000000000;
parameter    ap_ST_st32_fsm_31 = 40'b10000000000000000000000000000000;
parameter    ap_ST_st33_fsm_32 = 40'b100000000000000000000000000000000;
parameter    ap_ST_st34_fsm_33 = 40'b1000000000000000000000000000000000;
parameter    ap_ST_st35_fsm_34 = 40'b10000000000000000000000000000000000;
parameter    ap_ST_st36_fsm_35 = 40'b100000000000000000000000000000000000;
parameter    ap_ST_st37_fsm_36 = 40'b1000000000000000000000000000000000000;
parameter    ap_ST_st38_fsm_37 = 40'b10000000000000000000000000000000000000;
parameter    ap_ST_st39_fsm_38 = 40'b100000000000000000000000000000000000000;
parameter    ap_ST_st40_fsm_39 = 40'b1000000000000000000000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_1C = 32'b11100;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv32_22 = 32'b100010;
parameter    ap_const_lv32_24 = 32'b100100;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_19 = 32'b11001;
parameter    ap_const_lv32_1D = 32'b11101;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_23 = 32'b100011;
parameter    ap_const_lv32_25 = 32'b100101;
parameter    ap_const_lv4_3 = 4'b11;
parameter    ap_const_lv4_2 = 4'b10;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv4_C = 4'b1100;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_1A = 32'b11010;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_26 = 32'b100110;
parameter    ap_const_lv25_1E8480 = 25'b111101000010010000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv25_7A120 = 25'b1111010000100100000;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv25_C350 = 25'b1100001101010000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv25_2710 = 25'b10011100010000;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_1B = 32'b11011;
parameter    ap_const_lv25_30D40 = 25'b110000110101000000;
parameter    ap_const_lv32_21 = 32'b100001;
parameter    ap_const_lv32_27 = 32'b100111;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] dummy_tmr_out_i;
output  [0:0] dummy_tmr_out_o;
output   dummy_tmr_out_o_ap_vld;
output  [0:0] en;
output   en_ap_vld;
output  [0:0] rs;
output   rs_ap_vld;
output  [3:0] data;
output   data_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] dummy_tmr_out_o;
reg dummy_tmr_out_o_ap_vld;
reg en_ap_vld;
reg rs_ap_vld;
reg data_ap_vld;

(* fsm_encoding = "none" *) reg   [39:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_57;
wire    grp_lcddrv_lcd_send_cmd_fu_36_ap_start;
wire    grp_lcddrv_lcd_send_cmd_fu_36_ap_done;
wire    grp_lcddrv_lcd_send_cmd_fu_36_ap_idle;
wire    grp_lcddrv_lcd_send_cmd_fu_36_ap_ready;
reg   [3:0] grp_lcddrv_lcd_send_cmd_fu_36_wd;
wire   [0:0] grp_lcddrv_lcd_send_cmd_fu_36_en;
wire    grp_lcddrv_lcd_send_cmd_fu_36_en_ap_vld;
wire   [0:0] grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o;
wire    grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld;
wire   [0:0] grp_lcddrv_lcd_send_cmd_fu_36_rs;
wire    grp_lcddrv_lcd_send_cmd_fu_36_rs_ap_vld;
wire   [3:0] grp_lcddrv_lcd_send_cmd_fu_36_data;
wire    grp_lcddrv_lcd_send_cmd_fu_36_data_ap_vld;
wire    grp_lcddrv_wait_tmr_fu_57_ap_start;
wire    grp_lcddrv_wait_tmr_fu_57_ap_done;
wire    grp_lcddrv_wait_tmr_fu_57_ap_idle;
wire    grp_lcddrv_wait_tmr_fu_57_ap_ready;
reg   [24:0] grp_lcddrv_wait_tmr_fu_57_tmr;
wire   [0:0] grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o;
wire    grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o_ap_vld;
reg    ap_reg_grp_lcddrv_lcd_send_cmd_fu_36_ap_start;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_105;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_112;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_120;
reg    ap_sig_cseq_ST_st15_fsm_14;
reg    ap_sig_128;
reg    ap_sig_cseq_ST_st17_fsm_16;
reg    ap_sig_136;
reg    ap_sig_cseq_ST_st19_fsm_18;
reg    ap_sig_144;
reg    ap_sig_cseq_ST_st23_fsm_22;
reg    ap_sig_152;
reg    ap_sig_cseq_ST_st25_fsm_24;
reg    ap_sig_160;
reg    ap_sig_cseq_ST_st29_fsm_28;
reg    ap_sig_168;
reg    ap_sig_cseq_ST_st31_fsm_30;
reg    ap_sig_176;
reg    ap_sig_cseq_ST_st35_fsm_34;
reg    ap_sig_184;
reg    ap_sig_cseq_ST_st37_fsm_36;
reg    ap_sig_192;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_201;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_208;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_216;
reg    ap_sig_cseq_ST_st16_fsm_15;
reg    ap_sig_224;
reg    ap_sig_cseq_ST_st18_fsm_17;
reg    ap_sig_232;
reg    ap_sig_cseq_ST_st20_fsm_19;
reg    ap_sig_240;
reg    ap_sig_cseq_ST_st24_fsm_23;
reg    ap_sig_248;
reg    ap_sig_cseq_ST_st26_fsm_25;
reg    ap_sig_256;
reg    ap_sig_cseq_ST_st30_fsm_29;
reg    ap_sig_264;
reg    ap_sig_cseq_ST_st32_fsm_31;
reg    ap_sig_272;
reg    ap_sig_cseq_ST_st36_fsm_35;
reg    ap_sig_280;
reg    ap_sig_cseq_ST_st38_fsm_37;
reg    ap_sig_288;
reg    ap_reg_grp_lcddrv_wait_tmr_fu_57_ap_start;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_407;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_415;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_423;
reg    ap_sig_cseq_ST_st21_fsm_20;
reg    ap_sig_431;
reg    ap_sig_cseq_ST_st27_fsm_26;
reg    ap_sig_439;
reg    ap_sig_cseq_ST_st33_fsm_32;
reg    ap_sig_447;
reg    ap_sig_cseq_ST_st39_fsm_38;
reg    ap_sig_455;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_464;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_472;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_480;
reg    ap_sig_cseq_ST_st14_fsm_13;
reg    ap_sig_487;
reg    ap_sig_cseq_ST_st22_fsm_21;
reg    ap_sig_496;
reg    ap_sig_cseq_ST_st28_fsm_27;
reg    ap_sig_503;
reg    ap_sig_cseq_ST_st34_fsm_33;
reg    ap_sig_512;
reg    ap_sig_cseq_ST_st40_fsm_39;
reg    ap_sig_519;
reg   [39:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 40'b1;
#0 ap_reg_grp_lcddrv_lcd_send_cmd_fu_36_ap_start = 1'b0;
#0 ap_reg_grp_lcddrv_wait_tmr_fu_57_ap_start = 1'b0;
end

lcddrv_lcd_send_cmd grp_lcddrv_lcd_send_cmd_fu_36(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_lcddrv_lcd_send_cmd_fu_36_ap_start),
    .ap_done(grp_lcddrv_lcd_send_cmd_fu_36_ap_done),
    .ap_idle(grp_lcddrv_lcd_send_cmd_fu_36_ap_idle),
    .ap_ready(grp_lcddrv_lcd_send_cmd_fu_36_ap_ready),
    .mode(1'b0),
    .wd(grp_lcddrv_lcd_send_cmd_fu_36_wd),
    .en(grp_lcddrv_lcd_send_cmd_fu_36_en),
    .en_ap_vld(grp_lcddrv_lcd_send_cmd_fu_36_en_ap_vld),
    .dummy_tmr_out_i(dummy_tmr_out_i),
    .dummy_tmr_out_o(grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o),
    .dummy_tmr_out_o_ap_vld(grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld),
    .rs(grp_lcddrv_lcd_send_cmd_fu_36_rs),
    .rs_ap_vld(grp_lcddrv_lcd_send_cmd_fu_36_rs_ap_vld),
    .data(grp_lcddrv_lcd_send_cmd_fu_36_data),
    .data_ap_vld(grp_lcddrv_lcd_send_cmd_fu_36_data_ap_vld)
);

lcddrv_wait_tmr grp_lcddrv_wait_tmr_fu_57(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_lcddrv_wait_tmr_fu_57_ap_start),
    .ap_done(grp_lcddrv_wait_tmr_fu_57_ap_done),
    .ap_idle(grp_lcddrv_wait_tmr_fu_57_ap_idle),
    .ap_ready(grp_lcddrv_wait_tmr_fu_57_ap_ready),
    .tmr(grp_lcddrv_wait_tmr_fu_57_tmr),
    .dummy_tmr_out_i(dummy_tmr_out_i),
    .dummy_tmr_out_o(grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o),
    .dummy_tmr_out_o_ap_vld(grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_lcddrv_lcd_send_cmd_fu_36_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) | (1'b1 == ap_sig_cseq_ST_st7_fsm_6) | (1'b1 == ap_sig_cseq_ST_st11_fsm_10) | (1'b1 == ap_sig_cseq_ST_st15_fsm_14) | (1'b1 == ap_sig_cseq_ST_st17_fsm_16) | (1'b1 == ap_sig_cseq_ST_st19_fsm_18) | (1'b1 == ap_sig_cseq_ST_st23_fsm_22) | (1'b1 == ap_sig_cseq_ST_st25_fsm_24) | (1'b1 == ap_sig_cseq_ST_st29_fsm_28) | (1'b1 == ap_sig_cseq_ST_st31_fsm_30) | (1'b1 == ap_sig_cseq_ST_st35_fsm_34) | (1'b1 == ap_sig_cseq_ST_st37_fsm_36))) begin
            ap_reg_grp_lcddrv_lcd_send_cmd_fu_36_ap_start <= 1'b1;
        end else if ((1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_ap_ready)) begin
            ap_reg_grp_lcddrv_lcd_send_cmd_fu_36_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_lcddrv_wait_tmr_fu_57_ap_start <= 1'b0;
    end else begin
        if ((((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0)) | (1'b1 == ap_sig_cseq_ST_st5_fsm_4) | (1'b1 == ap_sig_cseq_ST_st9_fsm_8) | (1'b1 == ap_sig_cseq_ST_st13_fsm_12) | (1'b1 == ap_sig_cseq_ST_st21_fsm_20) | (1'b1 == ap_sig_cseq_ST_st27_fsm_26) | (1'b1 == ap_sig_cseq_ST_st33_fsm_32) | (1'b1 == ap_sig_cseq_ST_st39_fsm_38))) begin
            ap_reg_grp_lcddrv_wait_tmr_fu_57_ap_start <= 1'b1;
        end else if ((1'b1 == grp_lcddrv_wait_tmr_fu_57_ap_ready)) begin
            ap_reg_grp_lcddrv_wait_tmr_fu_57_ap_start <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | ((1'b1 == ap_sig_cseq_ST_st40_fsm_39) & ~(1'b0 == grp_lcddrv_wait_tmr_fu_57_ap_done)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st40_fsm_39) & ~(1'b0 == grp_lcddrv_wait_tmr_fu_57_ap_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_480) begin
        ap_sig_cseq_ST_st10_fsm_9 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_120) begin
        ap_sig_cseq_ST_st11_fsm_10 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_216) begin
        ap_sig_cseq_ST_st12_fsm_11 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_423) begin
        ap_sig_cseq_ST_st13_fsm_12 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_487) begin
        ap_sig_cseq_ST_st14_fsm_13 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_13 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_128) begin
        ap_sig_cseq_ST_st15_fsm_14 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_14 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_224) begin
        ap_sig_cseq_ST_st16_fsm_15 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st16_fsm_15 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_136) begin
        ap_sig_cseq_ST_st17_fsm_16 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st17_fsm_16 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_232) begin
        ap_sig_cseq_ST_st18_fsm_17 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_17 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_144) begin
        ap_sig_cseq_ST_st19_fsm_18 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_18 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_57) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_240) begin
        ap_sig_cseq_ST_st20_fsm_19 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_19 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_431) begin
        ap_sig_cseq_ST_st21_fsm_20 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st21_fsm_20 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_496) begin
        ap_sig_cseq_ST_st22_fsm_21 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st22_fsm_21 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_152) begin
        ap_sig_cseq_ST_st23_fsm_22 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st23_fsm_22 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_248) begin
        ap_sig_cseq_ST_st24_fsm_23 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st24_fsm_23 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_160) begin
        ap_sig_cseq_ST_st25_fsm_24 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st25_fsm_24 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_256) begin
        ap_sig_cseq_ST_st26_fsm_25 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st26_fsm_25 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_439) begin
        ap_sig_cseq_ST_st27_fsm_26 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st27_fsm_26 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_503) begin
        ap_sig_cseq_ST_st28_fsm_27 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st28_fsm_27 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_168) begin
        ap_sig_cseq_ST_st29_fsm_28 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st29_fsm_28 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_464) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_264) begin
        ap_sig_cseq_ST_st30_fsm_29 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st30_fsm_29 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_176) begin
        ap_sig_cseq_ST_st31_fsm_30 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st31_fsm_30 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_272) begin
        ap_sig_cseq_ST_st32_fsm_31 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st32_fsm_31 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_447) begin
        ap_sig_cseq_ST_st33_fsm_32 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st33_fsm_32 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_512) begin
        ap_sig_cseq_ST_st34_fsm_33 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st34_fsm_33 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_184) begin
        ap_sig_cseq_ST_st35_fsm_34 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st35_fsm_34 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_280) begin
        ap_sig_cseq_ST_st36_fsm_35 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st36_fsm_35 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_192) begin
        ap_sig_cseq_ST_st37_fsm_36 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st37_fsm_36 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_288) begin
        ap_sig_cseq_ST_st38_fsm_37 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st38_fsm_37 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_455) begin
        ap_sig_cseq_ST_st39_fsm_38 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st39_fsm_38 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_105) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_519) begin
        ap_sig_cseq_ST_st40_fsm_39 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st40_fsm_39 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_201) begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_407) begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_472) begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_112) begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_208) begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_415) begin
        ap_sig_cseq_ST_st9_fsm_8 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) | (1'b1 == ap_sig_cseq_ST_st8_fsm_7) | (1'b1 == ap_sig_cseq_ST_st12_fsm_11) | (1'b1 == ap_sig_cseq_ST_st16_fsm_15) | (1'b1 == ap_sig_cseq_ST_st18_fsm_17) | (1'b1 == ap_sig_cseq_ST_st20_fsm_19) | (1'b1 == ap_sig_cseq_ST_st24_fsm_23) | (1'b1 == ap_sig_cseq_ST_st26_fsm_25) | (1'b1 == ap_sig_cseq_ST_st30_fsm_29) | (1'b1 == ap_sig_cseq_ST_st32_fsm_31) | (1'b1 == ap_sig_cseq_ST_st36_fsm_35) | (1'b1 == ap_sig_cseq_ST_st38_fsm_37))) begin
        data_ap_vld = grp_lcddrv_lcd_send_cmd_fu_36_data_ap_vld;
    end else begin
        data_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b1 == grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & (1'b1 == grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st10_fsm_9) & (1'b1 == grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st14_fsm_13) & (1'b1 == grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st22_fsm_21) & (1'b1 == grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st28_fsm_27) & (1'b1 == grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st34_fsm_33) & (1'b1 == grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st40_fsm_39) & (1'b1 == grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o_ap_vld)))) begin
        dummy_tmr_out_o = grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o;
    end else if ((((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & (1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st8_fsm_7) & (1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st12_fsm_11) & (1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st16_fsm_15) & (1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st18_fsm_17) & (1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st20_fsm_19) & (1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st24_fsm_23) & (1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st26_fsm_25) & (1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st30_fsm_29) & (1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st32_fsm_31) & (1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st36_fsm_35) & (1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st38_fsm_37) & (1'b1 == grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld)))) begin
        dummy_tmr_out_o = grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o;
    end else begin
        dummy_tmr_out_o = dummy_tmr_out_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) | (1'b1 == ap_sig_cseq_ST_st6_fsm_5) | (1'b1 == ap_sig_cseq_ST_st10_fsm_9) | (1'b1 == ap_sig_cseq_ST_st14_fsm_13) | (1'b1 == ap_sig_cseq_ST_st22_fsm_21) | (1'b1 == ap_sig_cseq_ST_st28_fsm_27) | (1'b1 == ap_sig_cseq_ST_st34_fsm_33) | (1'b1 == ap_sig_cseq_ST_st40_fsm_39))) begin
        dummy_tmr_out_o_ap_vld = grp_lcddrv_wait_tmr_fu_57_dummy_tmr_out_o_ap_vld;
    end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) | (1'b1 == ap_sig_cseq_ST_st8_fsm_7) | (1'b1 == ap_sig_cseq_ST_st12_fsm_11) | (1'b1 == ap_sig_cseq_ST_st16_fsm_15) | (1'b1 == ap_sig_cseq_ST_st18_fsm_17) | (1'b1 == ap_sig_cseq_ST_st20_fsm_19) | (1'b1 == ap_sig_cseq_ST_st24_fsm_23) | (1'b1 == ap_sig_cseq_ST_st26_fsm_25) | (1'b1 == ap_sig_cseq_ST_st30_fsm_29) | (1'b1 == ap_sig_cseq_ST_st32_fsm_31) | (1'b1 == ap_sig_cseq_ST_st36_fsm_35) | (1'b1 == ap_sig_cseq_ST_st38_fsm_37))) begin
        dummy_tmr_out_o_ap_vld = grp_lcddrv_lcd_send_cmd_fu_36_dummy_tmr_out_o_ap_vld;
    end else begin
        dummy_tmr_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) | (1'b1 == ap_sig_cseq_ST_st8_fsm_7) | (1'b1 == ap_sig_cseq_ST_st12_fsm_11) | (1'b1 == ap_sig_cseq_ST_st16_fsm_15) | (1'b1 == ap_sig_cseq_ST_st18_fsm_17) | (1'b1 == ap_sig_cseq_ST_st20_fsm_19) | (1'b1 == ap_sig_cseq_ST_st24_fsm_23) | (1'b1 == ap_sig_cseq_ST_st26_fsm_25) | (1'b1 == ap_sig_cseq_ST_st30_fsm_29) | (1'b1 == ap_sig_cseq_ST_st32_fsm_31) | (1'b1 == ap_sig_cseq_ST_st36_fsm_35) | (1'b1 == ap_sig_cseq_ST_st38_fsm_37))) begin
        en_ap_vld = grp_lcddrv_lcd_send_cmd_fu_36_en_ap_vld;
    end else begin
        en_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st32_fsm_31)) begin
        grp_lcddrv_lcd_send_cmd_fu_36_wd = ap_const_lv4_1;
    end else if ((1'b1 == ap_sig_cseq_ST_st26_fsm_25)) begin
        grp_lcddrv_lcd_send_cmd_fu_36_wd = ap_const_lv4_C;
    end else if (((1'b1 == ap_sig_cseq_ST_st24_fsm_23) | (1'b1 == ap_sig_cseq_ST_st30_fsm_29) | (1'b1 == ap_sig_cseq_ST_st36_fsm_35))) begin
        grp_lcddrv_lcd_send_cmd_fu_36_wd = ap_const_lv4_0;
    end else if ((1'b1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        grp_lcddrv_lcd_send_cmd_fu_36_wd = ap_const_lv4_8;
    end else if (((1'b1 == ap_sig_cseq_ST_st16_fsm_15) | (1'b1 == ap_sig_cseq_ST_st18_fsm_17) | (1'b1 == ap_sig_cseq_ST_st38_fsm_37))) begin
        grp_lcddrv_lcd_send_cmd_fu_36_wd = ap_const_lv4_2;
    end else if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) | (1'b1 == ap_sig_cseq_ST_st8_fsm_7) | (1'b1 == ap_sig_cseq_ST_st12_fsm_11))) begin
        grp_lcddrv_lcd_send_cmd_fu_36_wd = ap_const_lv4_3;
    end else begin
        grp_lcddrv_lcd_send_cmd_fu_36_wd = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st34_fsm_33)) begin
        grp_lcddrv_wait_tmr_fu_57_tmr = ap_const_lv25_30D40;
    end else if (((1'b1 == ap_sig_cseq_ST_st22_fsm_21) | (1'b1 == ap_sig_cseq_ST_st28_fsm_27) | (1'b1 == ap_sig_cseq_ST_st40_fsm_39))) begin
        grp_lcddrv_wait_tmr_fu_57_tmr = ap_const_lv25_2710;
    end else if (((1'b1 == ap_sig_cseq_ST_st10_fsm_9) | (1'b1 == ap_sig_cseq_ST_st14_fsm_13))) begin
        grp_lcddrv_wait_tmr_fu_57_tmr = ap_const_lv25_C350;
    end else if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        grp_lcddrv_wait_tmr_fu_57_tmr = ap_const_lv25_7A120;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        grp_lcddrv_wait_tmr_fu_57_tmr = ap_const_lv25_1E8480;
    end else begin
        grp_lcddrv_wait_tmr_fu_57_tmr = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) | (1'b1 == ap_sig_cseq_ST_st8_fsm_7) | (1'b1 == ap_sig_cseq_ST_st12_fsm_11) | (1'b1 == ap_sig_cseq_ST_st16_fsm_15) | (1'b1 == ap_sig_cseq_ST_st18_fsm_17) | (1'b1 == ap_sig_cseq_ST_st20_fsm_19) | (1'b1 == ap_sig_cseq_ST_st24_fsm_23) | (1'b1 == ap_sig_cseq_ST_st26_fsm_25) | (1'b1 == ap_sig_cseq_ST_st30_fsm_29) | (1'b1 == ap_sig_cseq_ST_st32_fsm_31) | (1'b1 == ap_sig_cseq_ST_st36_fsm_35) | (1'b1 == ap_sig_cseq_ST_st38_fsm_37))) begin
        rs_ap_vld = grp_lcddrv_lcd_send_cmd_fu_36_rs_ap_vld;
    end else begin
        rs_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if (~(1'b0 == grp_lcddrv_wait_tmr_fu_57_ap_done)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : begin
            if (~(1'b0 == grp_lcddrv_lcd_send_cmd_fu_36_ap_done)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st5_fsm_4 : begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : begin
            if (~(1'b0 == grp_lcddrv_wait_tmr_fu_57_ap_done)) begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end
        end
        ap_ST_st7_fsm_6 : begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : begin
            if (~(1'b0 == grp_lcddrv_lcd_send_cmd_fu_36_ap_done)) begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end
        end
        ap_ST_st9_fsm_8 : begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : begin
            if (~(1'b0 == grp_lcddrv_wait_tmr_fu_57_ap_done)) begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end else begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end
        end
        ap_ST_st11_fsm_10 : begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : begin
            if (~(1'b0 == grp_lcddrv_lcd_send_cmd_fu_36_ap_done)) begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end else begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end
        end
        ap_ST_st13_fsm_12 : begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : begin
            if (~(1'b0 == grp_lcddrv_wait_tmr_fu_57_ap_done)) begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end else begin
                ap_NS_fsm = ap_ST_st14_fsm_13;
            end
        end
        ap_ST_st15_fsm_14 : begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st16_fsm_15 : begin
            if (~(1'b0 == grp_lcddrv_lcd_send_cmd_fu_36_ap_done)) begin
                ap_NS_fsm = ap_ST_st17_fsm_16;
            end else begin
                ap_NS_fsm = ap_ST_st16_fsm_15;
            end
        end
        ap_ST_st17_fsm_16 : begin
            ap_NS_fsm = ap_ST_st18_fsm_17;
        end
        ap_ST_st18_fsm_17 : begin
            if (~(1'b0 == grp_lcddrv_lcd_send_cmd_fu_36_ap_done)) begin
                ap_NS_fsm = ap_ST_st19_fsm_18;
            end else begin
                ap_NS_fsm = ap_ST_st18_fsm_17;
            end
        end
        ap_ST_st19_fsm_18 : begin
            ap_NS_fsm = ap_ST_st20_fsm_19;
        end
        ap_ST_st20_fsm_19 : begin
            if (~(1'b0 == grp_lcddrv_lcd_send_cmd_fu_36_ap_done)) begin
                ap_NS_fsm = ap_ST_st21_fsm_20;
            end else begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end
        end
        ap_ST_st21_fsm_20 : begin
            ap_NS_fsm = ap_ST_st22_fsm_21;
        end
        ap_ST_st22_fsm_21 : begin
            if (~(1'b0 == grp_lcddrv_wait_tmr_fu_57_ap_done)) begin
                ap_NS_fsm = ap_ST_st23_fsm_22;
            end else begin
                ap_NS_fsm = ap_ST_st22_fsm_21;
            end
        end
        ap_ST_st23_fsm_22 : begin
            ap_NS_fsm = ap_ST_st24_fsm_23;
        end
        ap_ST_st24_fsm_23 : begin
            if (~(1'b0 == grp_lcddrv_lcd_send_cmd_fu_36_ap_done)) begin
                ap_NS_fsm = ap_ST_st25_fsm_24;
            end else begin
                ap_NS_fsm = ap_ST_st24_fsm_23;
            end
        end
        ap_ST_st25_fsm_24 : begin
            ap_NS_fsm = ap_ST_st26_fsm_25;
        end
        ap_ST_st26_fsm_25 : begin
            if (~(1'b0 == grp_lcddrv_lcd_send_cmd_fu_36_ap_done)) begin
                ap_NS_fsm = ap_ST_st27_fsm_26;
            end else begin
                ap_NS_fsm = ap_ST_st26_fsm_25;
            end
        end
        ap_ST_st27_fsm_26 : begin
            ap_NS_fsm = ap_ST_st28_fsm_27;
        end
        ap_ST_st28_fsm_27 : begin
            if (~(1'b0 == grp_lcddrv_wait_tmr_fu_57_ap_done)) begin
                ap_NS_fsm = ap_ST_st29_fsm_28;
            end else begin
                ap_NS_fsm = ap_ST_st28_fsm_27;
            end
        end
        ap_ST_st29_fsm_28 : begin
            ap_NS_fsm = ap_ST_st30_fsm_29;
        end
        ap_ST_st30_fsm_29 : begin
            if (~(1'b0 == grp_lcddrv_lcd_send_cmd_fu_36_ap_done)) begin
                ap_NS_fsm = ap_ST_st31_fsm_30;
            end else begin
                ap_NS_fsm = ap_ST_st30_fsm_29;
            end
        end
        ap_ST_st31_fsm_30 : begin
            ap_NS_fsm = ap_ST_st32_fsm_31;
        end
        ap_ST_st32_fsm_31 : begin
            if (~(1'b0 == grp_lcddrv_lcd_send_cmd_fu_36_ap_done)) begin
                ap_NS_fsm = ap_ST_st33_fsm_32;
            end else begin
                ap_NS_fsm = ap_ST_st32_fsm_31;
            end
        end
        ap_ST_st33_fsm_32 : begin
            ap_NS_fsm = ap_ST_st34_fsm_33;
        end
        ap_ST_st34_fsm_33 : begin
            if (~(1'b0 == grp_lcddrv_wait_tmr_fu_57_ap_done)) begin
                ap_NS_fsm = ap_ST_st35_fsm_34;
            end else begin
                ap_NS_fsm = ap_ST_st34_fsm_33;
            end
        end
        ap_ST_st35_fsm_34 : begin
            ap_NS_fsm = ap_ST_st36_fsm_35;
        end
        ap_ST_st36_fsm_35 : begin
            if (~(1'b0 == grp_lcddrv_lcd_send_cmd_fu_36_ap_done)) begin
                ap_NS_fsm = ap_ST_st37_fsm_36;
            end else begin
                ap_NS_fsm = ap_ST_st36_fsm_35;
            end
        end
        ap_ST_st37_fsm_36 : begin
            ap_NS_fsm = ap_ST_st38_fsm_37;
        end
        ap_ST_st38_fsm_37 : begin
            if (~(1'b0 == grp_lcddrv_lcd_send_cmd_fu_36_ap_done)) begin
                ap_NS_fsm = ap_ST_st39_fsm_38;
            end else begin
                ap_NS_fsm = ap_ST_st38_fsm_37;
            end
        end
        ap_ST_st39_fsm_38 : begin
            ap_NS_fsm = ap_ST_st40_fsm_39;
        end
        ap_ST_st40_fsm_39 : begin
            if (~(1'b0 == grp_lcddrv_wait_tmr_fu_57_ap_done)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st40_fsm_39;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_sig_105 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_112 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_120 = (1'b1 == ap_CS_fsm[ap_const_lv32_A]);
end

always @ (*) begin
    ap_sig_128 = (1'b1 == ap_CS_fsm[ap_const_lv32_E]);
end

always @ (*) begin
    ap_sig_136 = (1'b1 == ap_CS_fsm[ap_const_lv32_10]);
end

always @ (*) begin
    ap_sig_144 = (1'b1 == ap_CS_fsm[ap_const_lv32_12]);
end

always @ (*) begin
    ap_sig_152 = (1'b1 == ap_CS_fsm[ap_const_lv32_16]);
end

always @ (*) begin
    ap_sig_160 = (1'b1 == ap_CS_fsm[ap_const_lv32_18]);
end

always @ (*) begin
    ap_sig_168 = (1'b1 == ap_CS_fsm[ap_const_lv32_1C]);
end

always @ (*) begin
    ap_sig_176 = (1'b1 == ap_CS_fsm[ap_const_lv32_1E]);
end

always @ (*) begin
    ap_sig_184 = (1'b1 == ap_CS_fsm[ap_const_lv32_22]);
end

always @ (*) begin
    ap_sig_192 = (1'b1 == ap_CS_fsm[ap_const_lv32_24]);
end

always @ (*) begin
    ap_sig_201 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_208 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_216 = (1'b1 == ap_CS_fsm[ap_const_lv32_B]);
end

always @ (*) begin
    ap_sig_224 = (1'b1 == ap_CS_fsm[ap_const_lv32_F]);
end

always @ (*) begin
    ap_sig_232 = (1'b1 == ap_CS_fsm[ap_const_lv32_11]);
end

always @ (*) begin
    ap_sig_240 = (1'b1 == ap_CS_fsm[ap_const_lv32_13]);
end

always @ (*) begin
    ap_sig_248 = (1'b1 == ap_CS_fsm[ap_const_lv32_17]);
end

always @ (*) begin
    ap_sig_256 = (1'b1 == ap_CS_fsm[ap_const_lv32_19]);
end

always @ (*) begin
    ap_sig_264 = (1'b1 == ap_CS_fsm[ap_const_lv32_1D]);
end

always @ (*) begin
    ap_sig_272 = (1'b1 == ap_CS_fsm[ap_const_lv32_1F]);
end

always @ (*) begin
    ap_sig_280 = (1'b1 == ap_CS_fsm[ap_const_lv32_23]);
end

always @ (*) begin
    ap_sig_288 = (1'b1 == ap_CS_fsm[ap_const_lv32_25]);
end

always @ (*) begin
    ap_sig_407 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_415 = (1'b1 == ap_CS_fsm[ap_const_lv32_8]);
end

always @ (*) begin
    ap_sig_423 = (1'b1 == ap_CS_fsm[ap_const_lv32_C]);
end

always @ (*) begin
    ap_sig_431 = (1'b1 == ap_CS_fsm[ap_const_lv32_14]);
end

always @ (*) begin
    ap_sig_439 = (1'b1 == ap_CS_fsm[ap_const_lv32_1A]);
end

always @ (*) begin
    ap_sig_447 = (1'b1 == ap_CS_fsm[ap_const_lv32_20]);
end

always @ (*) begin
    ap_sig_455 = (1'b1 == ap_CS_fsm[ap_const_lv32_26]);
end

always @ (*) begin
    ap_sig_464 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_472 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_480 = (1'b1 == ap_CS_fsm[ap_const_lv32_9]);
end

always @ (*) begin
    ap_sig_487 = (1'b1 == ap_CS_fsm[ap_const_lv32_D]);
end

always @ (*) begin
    ap_sig_496 = (1'b1 == ap_CS_fsm[ap_const_lv32_15]);
end

always @ (*) begin
    ap_sig_503 = (1'b1 == ap_CS_fsm[ap_const_lv32_1B]);
end

always @ (*) begin
    ap_sig_512 = (1'b1 == ap_CS_fsm[ap_const_lv32_21]);
end

always @ (*) begin
    ap_sig_519 = (1'b1 == ap_CS_fsm[ap_const_lv32_27]);
end

always @ (*) begin
    ap_sig_57 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

assign data = grp_lcddrv_lcd_send_cmd_fu_36_data;

assign en = grp_lcddrv_lcd_send_cmd_fu_36_en;

assign grp_lcddrv_lcd_send_cmd_fu_36_ap_start = ap_reg_grp_lcddrv_lcd_send_cmd_fu_36_ap_start;

assign grp_lcddrv_wait_tmr_fu_57_ap_start = ap_reg_grp_lcddrv_wait_tmr_fu_57_ap_start;

assign rs = grp_lcddrv_lcd_send_cmd_fu_36_rs;

endmodule //lcddrv_init_lcd
