-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.1
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bno055_uart is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    dummy_tmr_out_i : IN STD_LOGIC_VECTOR (0 downto 0);
    dummy_tmr_out_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    uart_rx : IN STD_LOGIC_VECTOR (0 downto 0);
    uart_tx_i : IN STD_LOGIC_VECTOR (0 downto 0);
    uart_tx_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    mem_addr_i : IN STD_LOGIC_VECTOR (7 downto 0);
    mem_addr_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    mem_din : IN STD_LOGIC_VECTOR (7 downto 0);
    mem_dout_i : IN STD_LOGIC_VECTOR (7 downto 0);
    mem_dout_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    mem_wreq_i : IN STD_LOGIC_VECTOR (0 downto 0);
    mem_wreq_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    mem_wack : IN STD_LOGIC_VECTOR (0 downto 0);
    mem_rreq : IN STD_LOGIC_VECTOR (0 downto 0);
    mem_rack : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of bno055_uart is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "bno055_uart,hls_ip_2016_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35ticsg324-1l,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.180000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=1,HLS_SYN_FF=968,HLS_SYN_LUT=1501}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000000000001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000000000010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000000000100";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000000001000";
    constant ap_ST_st5_fsm_4 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000000010000";
    constant ap_ST_st6_fsm_5 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000000100000";
    constant ap_ST_st7_fsm_6 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000001000000";
    constant ap_ST_st8_fsm_7 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000010000000";
    constant ap_ST_st9_fsm_8 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000100000000";
    constant ap_ST_st10_fsm_9 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000001000000000";
    constant ap_ST_st11_fsm_10 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000010000000000";
    constant ap_ST_st12_fsm_11 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000100000000000";
    constant ap_ST_st13_fsm_12 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000001000000000000";
    constant ap_ST_st14_fsm_13 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000010000000000000";
    constant ap_ST_st15_fsm_14 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000100000000000000";
    constant ap_ST_st16_fsm_15 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000001000000000000000";
    constant ap_ST_st17_fsm_16 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000010000000000000000";
    constant ap_ST_st18_fsm_17 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000100000000000000000";
    constant ap_ST_st19_fsm_18 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000001000000000000000000";
    constant ap_ST_st20_fsm_19 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000010000000000000000000";
    constant ap_ST_st21_fsm_20 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000100000000000000000000";
    constant ap_ST_st22_fsm_21 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000001000000000000000000000";
    constant ap_ST_st23_fsm_22 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000010000000000000000000000";
    constant ap_ST_st24_fsm_23 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000100000000000000000000000";
    constant ap_ST_st25_fsm_24 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000001000000000000000000000000";
    constant ap_ST_st26_fsm_25 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000010000000000000000000000000";
    constant ap_ST_st27_fsm_26 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000100000000000000000000000000";
    constant ap_ST_st28_fsm_27 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000001000000000000000000000000000";
    constant ap_ST_st29_fsm_28 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000010000000000000000000000000000";
    constant ap_ST_st30_fsm_29 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000100000000000000000000000000000";
    constant ap_ST_st31_fsm_30 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000001000000000000000000000000000000";
    constant ap_ST_st32_fsm_31 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000010000000000000000000000000000000";
    constant ap_ST_st33_fsm_32 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000100000000000000000000000000000000";
    constant ap_ST_st34_fsm_33 : STD_LOGIC_VECTOR (42 downto 0) := "0000000001000000000000000000000000000000000";
    constant ap_ST_st35_fsm_34 : STD_LOGIC_VECTOR (42 downto 0) := "0000000010000000000000000000000000000000000";
    constant ap_ST_st36_fsm_35 : STD_LOGIC_VECTOR (42 downto 0) := "0000000100000000000000000000000000000000000";
    constant ap_ST_st37_fsm_36 : STD_LOGIC_VECTOR (42 downto 0) := "0000001000000000000000000000000000000000000";
    constant ap_ST_st38_fsm_37 : STD_LOGIC_VECTOR (42 downto 0) := "0000010000000000000000000000000000000000000";
    constant ap_ST_st39_fsm_38 : STD_LOGIC_VECTOR (42 downto 0) := "0000100000000000000000000000000000000000000";
    constant ap_ST_st40_fsm_39 : STD_LOGIC_VECTOR (42 downto 0) := "0001000000000000000000000000000000000000000";
    constant ap_ST_st41_fsm_40 : STD_LOGIC_VECTOR (42 downto 0) := "0010000000000000000000000000000000000000000";
    constant ap_ST_st42_fsm_41 : STD_LOGIC_VECTOR (42 downto 0) := "0100000000000000000000000000000000000000000";
    constant ap_ST_st43_fsm_42 : STD_LOGIC_VECTOR (42 downto 0) := "1000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv8_3E : STD_LOGIC_VECTOR (7 downto 0) := "00111110";
    constant ap_const_lv8_3D : STD_LOGIC_VECTOR (7 downto 0) := "00111101";
    constant ap_const_lv8_3B : STD_LOGIC_VECTOR (7 downto 0) := "00111011";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv7_7 : STD_LOGIC_VECTOR (6 downto 0) := "0000111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv7_3F : STD_LOGIC_VECTOR (6 downto 0) := "0111111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv7_3E : STD_LOGIC_VECTOR (6 downto 0) := "0111110";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv7_3D : STD_LOGIC_VECTOR (6 downto 0) := "0111101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv7_3B : STD_LOGIC_VECTOR (6 downto 0) := "0111011";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv8_C0 : STD_LOGIC_VECTOR (7 downto 0) := "11000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv28_5F5E100 : STD_LOGIC_VECTOR (27 downto 0) := "0101111101011110000100000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv28_989680 : STD_LOGIC_VECTOR (27 downto 0) := "0000100110001001011010000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv28_F4240 : STD_LOGIC_VECTOR (27 downto 0) := "0000000011110100001001000000";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv8_15 : STD_LOGIC_VECTOR (7 downto 0) := "00010101";
    constant ap_const_lv8_16 : STD_LOGIC_VECTOR (7 downto 0) := "00010110";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_85 : STD_LOGIC_VECTOR (7 downto 0) := "10000101";
    constant ap_const_lv8_83 : STD_LOGIC_VECTOR (7 downto 0) := "10000011";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv8_84 : STD_LOGIC_VECTOR (7 downto 0) := "10000100";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_C : STD_LOGIC_VECTOR (7 downto 0) := "00001100";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv20_64 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000001100100";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_58 : BOOLEAN;
    signal dummy_tmr_out_0_data_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal dummy_tmr_out_0_vld_reg : STD_LOGIC := '0';
    signal dummy_tmr_out_0_ack_out : STD_LOGIC;
    signal dummy_tmr_out_1_data_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal dummy_tmr_out_1_data_in : STD_LOGIC_VECTOR (0 downto 0);
    signal dummy_tmr_out_1_vld_reg : STD_LOGIC := '0';
    signal dummy_tmr_out_1_vld_in : STD_LOGIC;
    signal uart_tx_1_data_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal uart_tx_1_data_in : STD_LOGIC_VECTOR (0 downto 0);
    signal uart_tx_1_vld_reg : STD_LOGIC := '0';
    signal uart_tx_1_vld_in : STD_LOGIC;
    signal mem_addr_1_data_reg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal mem_addr_1_vld_reg : STD_LOGIC := '0';
    signal mem_addr_1_vld_in : STD_LOGIC;
    signal mem_dout_1_data_reg : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal mem_dout_1_vld_reg : STD_LOGIC := '0';
    signal mem_dout_1_vld_in : STD_LOGIC;
    signal mem_wreq_1_data_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal mem_wreq_1_vld_reg : STD_LOGIC := '0';
    signal mem_wreq_1_vld_in : STD_LOGIC;
    signal reg_292 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_cseq_ST_st19_fsm_18 : STD_LOGIC;
    signal ap_sig_353 : BOOLEAN;
    signal grp_bno055_uart_uart_read_reg_fu_210_ap_done : STD_LOGIC;
    signal ap_sig_cseq_ST_st31_fsm_30 : STD_LOGIC;
    signal ap_sig_364 : BOOLEAN;
    signal tmp_reg_400 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_cseq_ST_st13_fsm_12 : STD_LOGIC;
    signal ap_sig_375 : BOOLEAN;
    signal tmp_s_fu_307_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_reg_405 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st14_fsm_13 : STD_LOGIC;
    signal ap_sig_385 : BOOLEAN;
    signal tmp_4_fu_323_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_reg_410 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st20_fsm_19 : STD_LOGIC;
    signal ap_sig_394 : BOOLEAN;
    signal grp_bno055_uart_uart_read_reg_fu_210_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal dt_2_reg_415 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st25_fsm_24 : STD_LOGIC;
    signal ap_sig_403 : BOOLEAN;
    signal tmp_5_fu_330_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_reg_420 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st26_fsm_25 : STD_LOGIC;
    signal ap_sig_413 : BOOLEAN;
    signal tmp_10_fu_336_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_10_reg_425 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_trunc_ext_fu_340_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_trunc_ext_reg_430 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st32_fsm_31 : STD_LOGIC;
    signal ap_sig_424 : BOOLEAN;
    signal tmp_11_fu_345_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_reg_435 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st33_fsm_32 : STD_LOGIC;
    signal ap_sig_433 : BOOLEAN;
    signal grp_bno055_uart_write_mem_fu_254_ap_done : STD_LOGIC;
    signal grp_bno055_uart_uart_read_reg16_fu_200_ap_done : STD_LOGIC;
    signal e_tmp_1_reg_440 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_trunc2_ext_fu_359_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_trunc2_ext_reg_445 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st34_fsm_33 : STD_LOGIC;
    signal ap_sig_451 : BOOLEAN;
    signal tmp_2_reg_450 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st37_fsm_36 : STD_LOGIC;
    signal ap_sig_460 : BOOLEAN;
    signal tmp_6_reg_455 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_bno055_uart_uart_read_reg16_fu_200_ap_start : STD_LOGIC;
    signal grp_bno055_uart_uart_read_reg16_fu_200_ap_idle : STD_LOGIC;
    signal grp_bno055_uart_uart_read_reg16_fu_200_ap_ready : STD_LOGIC;
    signal grp_bno055_uart_uart_read_reg16_fu_200_uart_tx : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_bno055_uart_uart_read_reg16_fu_200_uart_tx_ap_vld : STD_LOGIC;
    signal grp_bno055_uart_uart_read_reg16_fu_200_dummy_tmr_out_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_bno055_uart_uart_read_reg16_fu_200_dummy_tmr_out_o_ap_vld : STD_LOGIC;
    signal grp_bno055_uart_uart_read_reg16_fu_200_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_bno055_uart_uart_read_reg_fu_210_ap_start : STD_LOGIC;
    signal grp_bno055_uart_uart_read_reg_fu_210_ap_idle : STD_LOGIC;
    signal grp_bno055_uart_uart_read_reg_fu_210_ap_ready : STD_LOGIC;
    signal grp_bno055_uart_uart_read_reg_fu_210_reg_addr : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_bno055_uart_uart_read_reg_fu_210_uart_tx : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_bno055_uart_uart_read_reg_fu_210_uart_tx_ap_vld : STD_LOGIC;
    signal grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o_ap_vld : STD_LOGIC;
    signal grp_bno055_uart_uart_write_reg_fu_225_ap_start : STD_LOGIC;
    signal grp_bno055_uart_uart_write_reg_fu_225_ap_done : STD_LOGIC;
    signal grp_bno055_uart_uart_write_reg_fu_225_ap_idle : STD_LOGIC;
    signal grp_bno055_uart_uart_write_reg_fu_225_ap_ready : STD_LOGIC;
    signal grp_bno055_uart_uart_write_reg_fu_225_reg_addr : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_bno055_uart_uart_write_reg_fu_225_data : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_bno055_uart_uart_write_reg_fu_225_uart_tx : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_bno055_uart_uart_write_reg_fu_225_uart_tx_ap_vld : STD_LOGIC;
    signal grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o_ap_vld : STD_LOGIC;
    signal grp_bno055_uart_wait_tmr_fu_244_ap_start : STD_LOGIC;
    signal grp_bno055_uart_wait_tmr_fu_244_ap_done : STD_LOGIC;
    signal grp_bno055_uart_wait_tmr_fu_244_ap_idle : STD_LOGIC;
    signal grp_bno055_uart_wait_tmr_fu_244_ap_ready : STD_LOGIC;
    signal grp_bno055_uart_wait_tmr_fu_244_tmr : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o_ap_vld : STD_LOGIC;
    signal grp_bno055_uart_write_mem_fu_254_ap_start : STD_LOGIC;
    signal grp_bno055_uart_write_mem_fu_254_ap_idle : STD_LOGIC;
    signal grp_bno055_uart_write_mem_fu_254_ap_ready : STD_LOGIC;
    signal grp_bno055_uart_write_mem_fu_254_addr : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_bno055_uart_write_mem_fu_254_data : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_bno055_uart_write_mem_fu_254_mem_addr : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_bno055_uart_write_mem_fu_254_mem_addr_ap_vld : STD_LOGIC;
    signal grp_bno055_uart_write_mem_fu_254_mem_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_bno055_uart_write_mem_fu_254_mem_dout_ap_vld : STD_LOGIC;
    signal grp_bno055_uart_write_mem_fu_254_mem_wreq : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_bno055_uart_write_mem_fu_254_mem_wreq_ap_vld : STD_LOGIC;
    signal grp_bno055_uart_bin2char_fu_277_val_r : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_bno055_uart_bin2char_fu_277_ap_return : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_reg_grp_bno055_uart_uart_read_reg16_fu_200_ap_start : STD_LOGIC := '0';
    signal ap_reg_grp_bno055_uart_uart_read_reg_fu_210_ap_start : STD_LOGIC := '0';
    signal ap_sig_cseq_ST_st12_fsm_11 : STD_LOGIC;
    signal ap_sig_545 : BOOLEAN;
    signal ap_sig_cseq_ST_st18_fsm_17 : STD_LOGIC;
    signal ap_sig_552 : BOOLEAN;
    signal ap_sig_cseq_ST_st24_fsm_23 : STD_LOGIC;
    signal ap_sig_560 : BOOLEAN;
    signal ap_sig_cseq_ST_st30_fsm_29 : STD_LOGIC;
    signal ap_sig_568 : BOOLEAN;
    signal ap_reg_grp_bno055_uart_uart_write_reg_fu_225_ap_start : STD_LOGIC := '0';
    signal ap_sig_cseq_ST_st4_fsm_3 : STD_LOGIC;
    signal ap_sig_600 : BOOLEAN;
    signal ap_sig_cseq_ST_st6_fsm_5 : STD_LOGIC;
    signal ap_sig_607 : BOOLEAN;
    signal ap_sig_cseq_ST_st10_fsm_9 : STD_LOGIC;
    signal ap_sig_615 : BOOLEAN;
    signal ap_sig_cseq_ST_st5_fsm_4 : STD_LOGIC;
    signal ap_sig_627 : BOOLEAN;
    signal ap_sig_cseq_ST_st7_fsm_6 : STD_LOGIC;
    signal ap_sig_635 : BOOLEAN;
    signal ap_sig_cseq_ST_st11_fsm_10 : STD_LOGIC;
    signal ap_sig_642 : BOOLEAN;
    signal ap_sig_cseq_ST_st15_fsm_14 : STD_LOGIC;
    signal ap_sig_651 : BOOLEAN;
    signal ap_sig_cseq_ST_st21_fsm_20 : STD_LOGIC;
    signal ap_sig_659 : BOOLEAN;
    signal ap_sig_cseq_ST_st27_fsm_26 : STD_LOGIC;
    signal ap_sig_667 : BOOLEAN;
    signal ap_reg_grp_bno055_uart_wait_tmr_fu_244_ap_start : STD_LOGIC := '0';
    signal ap_sig_cseq_ST_st8_fsm_7 : STD_LOGIC;
    signal ap_sig_706 : BOOLEAN;
    signal ap_sig_cseq_ST_st16_fsm_15 : STD_LOGIC;
    signal ap_sig_713 : BOOLEAN;
    signal ap_sig_cseq_ST_st22_fsm_21 : STD_LOGIC;
    signal ap_sig_721 : BOOLEAN;
    signal ap_sig_cseq_ST_st28_fsm_27 : STD_LOGIC;
    signal ap_sig_729 : BOOLEAN;
    signal ap_sig_cseq_ST_st9_fsm_8 : STD_LOGIC;
    signal ap_sig_739 : BOOLEAN;
    signal ap_sig_cseq_ST_st17_fsm_16 : STD_LOGIC;
    signal ap_sig_747 : BOOLEAN;
    signal ap_sig_cseq_ST_st23_fsm_22 : STD_LOGIC;
    signal ap_sig_754 : BOOLEAN;
    signal ap_sig_cseq_ST_st29_fsm_28 : STD_LOGIC;
    signal ap_sig_762 : BOOLEAN;
    signal ap_sig_cseq_ST_st35_fsm_34 : STD_LOGIC;
    signal ap_sig_771 : BOOLEAN;
    signal ap_reg_grp_bno055_uart_write_mem_fu_254_ap_start : STD_LOGIC := '0';
    signal ap_sig_cseq_ST_st36_fsm_35 : STD_LOGIC;
    signal ap_sig_796 : BOOLEAN;
    signal ap_sig_cseq_ST_st38_fsm_37 : STD_LOGIC;
    signal ap_sig_804 : BOOLEAN;
    signal ap_sig_cseq_ST_st40_fsm_39 : STD_LOGIC;
    signal ap_sig_812 : BOOLEAN;
    signal ap_sig_cseq_ST_st42_fsm_41 : STD_LOGIC;
    signal ap_sig_820 : BOOLEAN;
    signal ap_sig_cseq_ST_st39_fsm_38 : STD_LOGIC;
    signal ap_sig_833 : BOOLEAN;
    signal ap_sig_cseq_ST_st41_fsm_40 : STD_LOGIC;
    signal ap_sig_841 : BOOLEAN;
    signal ap_sig_cseq_ST_st43_fsm_42 : STD_LOGIC;
    signal ap_sig_848 : BOOLEAN;
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_912 : BOOLEAN;
    signal tmp_3_fu_315_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal e_fu_364_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_1_fu_392_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal e_1_fu_392_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal e_1_fu_392_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (42 downto 0);
    signal e_1_fu_392_p10 : STD_LOGIC_VECTOR (19 downto 0);

    component bno055_uart_uart_read_reg16 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        uart_tx : OUT STD_LOGIC_VECTOR (0 downto 0);
        uart_tx_ap_vld : OUT STD_LOGIC;
        dummy_tmr_out_i : IN STD_LOGIC_VECTOR (0 downto 0);
        dummy_tmr_out_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        dummy_tmr_out_o_ap_vld : OUT STD_LOGIC;
        uart_rx : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component bno055_uart_uart_read_reg IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        reg_addr : IN STD_LOGIC_VECTOR (7 downto 0);
        uart_tx : OUT STD_LOGIC_VECTOR (0 downto 0);
        uart_tx_ap_vld : OUT STD_LOGIC;
        dummy_tmr_out_i : IN STD_LOGIC_VECTOR (0 downto 0);
        dummy_tmr_out_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        dummy_tmr_out_o_ap_vld : OUT STD_LOGIC;
        uart_rx : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component bno055_uart_uart_write_reg IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        reg_addr : IN STD_LOGIC_VECTOR (6 downto 0);
        data : IN STD_LOGIC_VECTOR (7 downto 0);
        uart_tx : OUT STD_LOGIC_VECTOR (0 downto 0);
        uart_tx_ap_vld : OUT STD_LOGIC;
        dummy_tmr_out_i : IN STD_LOGIC_VECTOR (0 downto 0);
        dummy_tmr_out_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        dummy_tmr_out_o_ap_vld : OUT STD_LOGIC;
        uart_rx : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component bno055_uart_wait_tmr IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        tmr : IN STD_LOGIC_VECTOR (27 downto 0);
        dummy_tmr_out_i : IN STD_LOGIC_VECTOR (0 downto 0);
        dummy_tmr_out_o : OUT STD_LOGIC_VECTOR (0 downto 0);
        dummy_tmr_out_o_ap_vld : OUT STD_LOGIC );
    end component;


    component bno055_uart_write_mem IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        addr : IN STD_LOGIC_VECTOR (7 downto 0);
        data : IN STD_LOGIC_VECTOR (7 downto 0);
        mem_addr : OUT STD_LOGIC_VECTOR (7 downto 0);
        mem_addr_ap_vld : OUT STD_LOGIC;
        mem_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        mem_dout_ap_vld : OUT STD_LOGIC;
        mem_wreq : OUT STD_LOGIC_VECTOR (0 downto 0);
        mem_wreq_ap_vld : OUT STD_LOGIC;
        mem_wack : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component bno055_uart_bin2char IS
    port (
        val_r : IN STD_LOGIC_VECTOR (3 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component bno055_uart_mul_mul_8ns_16ns_20_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;



begin
    grp_bno055_uart_uart_read_reg16_fu_200 : component bno055_uart_uart_read_reg16
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bno055_uart_uart_read_reg16_fu_200_ap_start,
        ap_done => grp_bno055_uart_uart_read_reg16_fu_200_ap_done,
        ap_idle => grp_bno055_uart_uart_read_reg16_fu_200_ap_idle,
        ap_ready => grp_bno055_uart_uart_read_reg16_fu_200_ap_ready,
        uart_tx => grp_bno055_uart_uart_read_reg16_fu_200_uart_tx,
        uart_tx_ap_vld => grp_bno055_uart_uart_read_reg16_fu_200_uart_tx_ap_vld,
        dummy_tmr_out_i => dummy_tmr_out_0_data_reg,
        dummy_tmr_out_o => grp_bno055_uart_uart_read_reg16_fu_200_dummy_tmr_out_o,
        dummy_tmr_out_o_ap_vld => grp_bno055_uart_uart_read_reg16_fu_200_dummy_tmr_out_o_ap_vld,
        uart_rx => uart_rx,
        ap_return => grp_bno055_uart_uart_read_reg16_fu_200_ap_return);

    grp_bno055_uart_uart_read_reg_fu_210 : component bno055_uart_uart_read_reg
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bno055_uart_uart_read_reg_fu_210_ap_start,
        ap_done => grp_bno055_uart_uart_read_reg_fu_210_ap_done,
        ap_idle => grp_bno055_uart_uart_read_reg_fu_210_ap_idle,
        ap_ready => grp_bno055_uart_uart_read_reg_fu_210_ap_ready,
        reg_addr => grp_bno055_uart_uart_read_reg_fu_210_reg_addr,
        uart_tx => grp_bno055_uart_uart_read_reg_fu_210_uart_tx,
        uart_tx_ap_vld => grp_bno055_uart_uart_read_reg_fu_210_uart_tx_ap_vld,
        dummy_tmr_out_i => dummy_tmr_out_0_data_reg,
        dummy_tmr_out_o => grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o,
        dummy_tmr_out_o_ap_vld => grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o_ap_vld,
        uart_rx => uart_rx,
        ap_return => grp_bno055_uart_uart_read_reg_fu_210_ap_return);

    grp_bno055_uart_uart_write_reg_fu_225 : component bno055_uart_uart_write_reg
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bno055_uart_uart_write_reg_fu_225_ap_start,
        ap_done => grp_bno055_uart_uart_write_reg_fu_225_ap_done,
        ap_idle => grp_bno055_uart_uart_write_reg_fu_225_ap_idle,
        ap_ready => grp_bno055_uart_uart_write_reg_fu_225_ap_ready,
        reg_addr => grp_bno055_uart_uart_write_reg_fu_225_reg_addr,
        data => grp_bno055_uart_uart_write_reg_fu_225_data,
        uart_tx => grp_bno055_uart_uart_write_reg_fu_225_uart_tx,
        uart_tx_ap_vld => grp_bno055_uart_uart_write_reg_fu_225_uart_tx_ap_vld,
        dummy_tmr_out_i => dummy_tmr_out_0_data_reg,
        dummy_tmr_out_o => grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o,
        dummy_tmr_out_o_ap_vld => grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o_ap_vld,
        uart_rx => uart_rx);

    grp_bno055_uart_wait_tmr_fu_244 : component bno055_uart_wait_tmr
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bno055_uart_wait_tmr_fu_244_ap_start,
        ap_done => grp_bno055_uart_wait_tmr_fu_244_ap_done,
        ap_idle => grp_bno055_uart_wait_tmr_fu_244_ap_idle,
        ap_ready => grp_bno055_uart_wait_tmr_fu_244_ap_ready,
        tmr => grp_bno055_uart_wait_tmr_fu_244_tmr,
        dummy_tmr_out_i => dummy_tmr_out_0_data_reg,
        dummy_tmr_out_o => grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o,
        dummy_tmr_out_o_ap_vld => grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o_ap_vld);

    grp_bno055_uart_write_mem_fu_254 : component bno055_uart_write_mem
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bno055_uart_write_mem_fu_254_ap_start,
        ap_done => grp_bno055_uart_write_mem_fu_254_ap_done,
        ap_idle => grp_bno055_uart_write_mem_fu_254_ap_idle,
        ap_ready => grp_bno055_uart_write_mem_fu_254_ap_ready,
        addr => grp_bno055_uart_write_mem_fu_254_addr,
        data => grp_bno055_uart_write_mem_fu_254_data,
        mem_addr => grp_bno055_uart_write_mem_fu_254_mem_addr,
        mem_addr_ap_vld => grp_bno055_uart_write_mem_fu_254_mem_addr_ap_vld,
        mem_dout => grp_bno055_uart_write_mem_fu_254_mem_dout,
        mem_dout_ap_vld => grp_bno055_uart_write_mem_fu_254_mem_dout_ap_vld,
        mem_wreq => grp_bno055_uart_write_mem_fu_254_mem_wreq,
        mem_wreq_ap_vld => grp_bno055_uart_write_mem_fu_254_mem_wreq_ap_vld,
        mem_wack => mem_wack);

    grp_bno055_uart_bin2char_fu_277 : component bno055_uart_bin2char
    port map (
        val_r => grp_bno055_uart_bin2char_fu_277_val_r,
        ap_return => grp_bno055_uart_bin2char_fu_277_ap_return);

    bno055_uart_mul_mul_8ns_16ns_20_1_U27 : component bno055_uart_mul_mul_8ns_16ns_20_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 16,
        dout_WIDTH => 20)
    port map (
        din0 => e_1_fu_392_p0,
        din1 => e_1_fu_392_p1,
        dout => e_1_fu_392_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_grp_bno055_uart_uart_read_reg16_fu_200_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_bno055_uart_uart_read_reg16_fu_200_ap_start <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_cseq_ST_st32_fsm_31)) then 
                    ap_reg_grp_bno055_uart_uart_read_reg16_fu_200_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_bno055_uart_uart_read_reg16_fu_200_ap_ready)) then 
                    ap_reg_grp_bno055_uart_uart_read_reg16_fu_200_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_bno055_uart_uart_read_reg_fu_210_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_bno055_uart_uart_read_reg_fu_210_ap_start <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st12_fsm_11) or (ap_const_logic_1 = ap_sig_cseq_ST_st18_fsm_17) or (ap_const_logic_1 = ap_sig_cseq_ST_st24_fsm_23) or (ap_const_logic_1 = ap_sig_cseq_ST_st30_fsm_29))) then 
                    ap_reg_grp_bno055_uart_uart_read_reg_fu_210_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_bno055_uart_uart_read_reg_fu_210_ap_ready)) then 
                    ap_reg_grp_bno055_uart_uart_read_reg_fu_210_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_bno055_uart_uart_write_reg_fu_225_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_bno055_uart_uart_write_reg_fu_225_ap_start <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st14_fsm_13) or (ap_const_logic_1 = ap_sig_cseq_ST_st20_fsm_19) or (ap_const_logic_1 = ap_sig_cseq_ST_st26_fsm_25) or (ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) or (ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5) or (ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9))) then 
                    ap_reg_grp_bno055_uart_uart_write_reg_fu_225_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_ap_ready)) then 
                    ap_reg_grp_bno055_uart_uart_write_reg_fu_225_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_bno055_uart_wait_tmr_fu_244_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_bno055_uart_wait_tmr_fu_244_ap_start <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st34_fsm_33) or (ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7) or (ap_const_logic_1 = ap_sig_cseq_ST_st16_fsm_15) or (ap_const_logic_1 = ap_sig_cseq_ST_st22_fsm_21) or (ap_const_logic_1 = ap_sig_cseq_ST_st28_fsm_27))) then 
                    ap_reg_grp_bno055_uart_wait_tmr_fu_244_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_bno055_uart_wait_tmr_fu_244_ap_ready)) then 
                    ap_reg_grp_bno055_uart_wait_tmr_fu_244_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_bno055_uart_write_mem_fu_254_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_bno055_uart_write_mem_fu_254_ap_start <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st32_fsm_31) or (ap_const_logic_1 = ap_sig_cseq_ST_st34_fsm_33) or (ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) or (ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5) or (ap_const_logic_1 = ap_sig_cseq_ST_st36_fsm_35) or (ap_const_logic_1 = ap_sig_cseq_ST_st38_fsm_37) or (ap_const_logic_1 = ap_sig_cseq_ST_st40_fsm_39) or (ap_const_logic_1 = ap_sig_cseq_ST_st42_fsm_41))) then 
                    ap_reg_grp_bno055_uart_write_mem_fu_254_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_bno055_uart_write_mem_fu_254_ap_ready)) then 
                    ap_reg_grp_bno055_uart_write_mem_fu_254_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    dummy_tmr_out_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    dummy_tmr_out_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    mem_addr_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    mem_dout_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    mem_wreq_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    uart_tx_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_logic_0 = grp_bno055_uart_uart_read_reg_fu_210_ap_done)) and (ap_const_logic_1 = ap_sig_cseq_ST_st25_fsm_24))) then
                dt_2_reg_415 <= grp_bno055_uart_uart_read_reg_fu_210_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_0 = dummy_tmr_out_0_vld_reg)) or (not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = dummy_tmr_out_0_vld_reg) and (ap_const_logic_1 = dummy_tmr_out_0_ack_out)))) then
                dummy_tmr_out_0_data_reg <= dummy_tmr_out_i;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) and (ap_const_logic_1 = dummy_tmr_out_1_vld_in) and (ap_const_logic_0 = dummy_tmr_out_1_vld_reg)) or (not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) and (ap_const_logic_1 = dummy_tmr_out_1_vld_in) and (ap_const_logic_1 = dummy_tmr_out_1_vld_reg) and (ap_const_logic_1 = ap_const_logic_1)))) then
                dummy_tmr_out_1_data_reg <= dummy_tmr_out_1_data_in;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st33_fsm_32) and not(((ap_const_logic_0 = grp_bno055_uart_write_mem_fu_254_ap_done) or (ap_const_logic_0 = grp_bno055_uart_uart_read_reg16_fu_200_ap_done))))) then
                e_tmp_1_reg_440 <= grp_bno055_uart_uart_read_reg16_fu_200_ap_return(15 downto 8);
                tmp_11_reg_435 <= tmp_11_fu_345_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) and (ap_const_logic_1 = mem_addr_1_vld_in) and (ap_const_logic_0 = mem_addr_1_vld_reg)) or (not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) and (ap_const_logic_1 = mem_addr_1_vld_in) and (ap_const_logic_1 = mem_addr_1_vld_reg) and (ap_const_logic_1 = ap_const_logic_1)))) then
                mem_addr_1_data_reg <= grp_bno055_uart_write_mem_fu_254_mem_addr;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) and (ap_const_logic_1 = mem_dout_1_vld_in) and (ap_const_logic_0 = mem_dout_1_vld_reg)) or (not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) and (ap_const_logic_1 = mem_dout_1_vld_in) and (ap_const_logic_1 = mem_dout_1_vld_reg) and (ap_const_logic_1 = ap_const_logic_1)))) then
                mem_dout_1_data_reg <= grp_bno055_uart_write_mem_fu_254_mem_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) and (ap_const_logic_1 = mem_wreq_1_vld_in) and (ap_const_logic_0 = mem_wreq_1_vld_reg)) or (not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) and (ap_const_logic_1 = mem_wreq_1_vld_in) and (ap_const_logic_1 = mem_wreq_1_vld_reg) and (ap_const_logic_1 = ap_const_logic_1)))) then
                mem_wreq_1_data_reg <= grp_bno055_uart_write_mem_fu_254_mem_wreq;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st34_fsm_33)) then
                    p_trunc2_ext_reg_445(6 downto 0) <= p_trunc2_ext_fu_359_p1(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st32_fsm_31)) then
                    p_trunc_ext_reg_430(6 downto 0) <= p_trunc_ext_fu_340_p1(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_sig_cseq_ST_st19_fsm_18) and not((ap_const_logic_0 = grp_bno055_uart_uart_read_reg_fu_210_ap_done))) or (not((ap_const_logic_0 = grp_bno055_uart_uart_read_reg_fu_210_ap_done)) and (ap_const_logic_1 = ap_sig_cseq_ST_st31_fsm_30)))) then
                reg_292 <= grp_bno055_uart_uart_read_reg_fu_210_ap_return(7 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_logic_0 = grp_bno055_uart_uart_read_reg_fu_210_ap_done)) and (ap_const_logic_1 = ap_sig_cseq_ST_st31_fsm_30))) then
                tmp_10_reg_425 <= tmp_10_fu_336_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st37_fsm_36) and not((ap_const_logic_0 = grp_bno055_uart_write_mem_fu_254_ap_done)))) then
                tmp_2_reg_450 <= e_1_fu_392_p2(19 downto 12);
                tmp_6_reg_455 <= e_1_fu_392_p2(11 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st20_fsm_19)) then
                    tmp_4_reg_410(7 downto 4) <= tmp_4_fu_323_p2(7 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st26_fsm_25)) then
                    tmp_5_reg_420(6 downto 0) <= tmp_5_fu_330_p2(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_logic_0 = grp_bno055_uart_uart_read_reg_fu_210_ap_done)) and (ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12))) then
                tmp_reg_400 <= grp_bno055_uart_uart_read_reg_fu_210_ap_return(7 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st14_fsm_13)) then
                    tmp_s_reg_405(7 downto 2) <= tmp_s_fu_307_p3(7 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) and (ap_const_logic_1 = uart_tx_1_vld_in) and (ap_const_logic_0 = uart_tx_1_vld_reg)) or (not(((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) and (ap_const_logic_1 = uart_tx_1_vld_in) and (ap_const_logic_1 = uart_tx_1_vld_reg) and (ap_const_logic_1 = ap_const_logic_1)))) then
                uart_tx_1_data_reg <= uart_tx_1_data_in;
            end if;
        end if;
    end process;
    tmp_s_reg_405(1 downto 0) <= "00";
    tmp_4_reg_410(3 downto 0) <= "1100";
    tmp_5_reg_420(7) <= '1';
    p_trunc_ext_reg_430(7) <= '0';
    p_trunc2_ext_reg_445(7) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, grp_bno055_uart_uart_read_reg_fu_210_ap_done, grp_bno055_uart_write_mem_fu_254_ap_done, grp_bno055_uart_uart_read_reg16_fu_200_ap_done, grp_bno055_uart_uart_write_reg_fu_225_ap_done, grp_bno055_uart_wait_tmr_fu_244_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                ap_NS_fsm <= ap_ST_st3_fsm_2;
            when ap_ST_st3_fsm_2 => 
                ap_NS_fsm <= ap_ST_st4_fsm_3;
            when ap_ST_st4_fsm_3 => 
                ap_NS_fsm <= ap_ST_st5_fsm_4;
            when ap_ST_st5_fsm_4 => 
                if (not(((ap_const_logic_0 = grp_bno055_uart_write_mem_fu_254_ap_done) or (ap_const_logic_0 = grp_bno055_uart_uart_write_reg_fu_225_ap_done)))) then
                    ap_NS_fsm <= ap_ST_st6_fsm_5;
                else
                    ap_NS_fsm <= ap_ST_st5_fsm_4;
                end if;
            when ap_ST_st6_fsm_5 => 
                ap_NS_fsm <= ap_ST_st7_fsm_6;
            when ap_ST_st7_fsm_6 => 
                if (not(((ap_const_logic_0 = grp_bno055_uart_write_mem_fu_254_ap_done) or (ap_const_logic_0 = grp_bno055_uart_uart_write_reg_fu_225_ap_done)))) then
                    ap_NS_fsm <= ap_ST_st8_fsm_7;
                else
                    ap_NS_fsm <= ap_ST_st7_fsm_6;
                end if;
            when ap_ST_st8_fsm_7 => 
                ap_NS_fsm <= ap_ST_st9_fsm_8;
            when ap_ST_st9_fsm_8 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_wait_tmr_fu_244_ap_done))) then
                    ap_NS_fsm <= ap_ST_st10_fsm_9;
                else
                    ap_NS_fsm <= ap_ST_st9_fsm_8;
                end if;
            when ap_ST_st10_fsm_9 => 
                ap_NS_fsm <= ap_ST_st11_fsm_10;
            when ap_ST_st11_fsm_10 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_uart_write_reg_fu_225_ap_done))) then
                    ap_NS_fsm <= ap_ST_st12_fsm_11;
                else
                    ap_NS_fsm <= ap_ST_st11_fsm_10;
                end if;
            when ap_ST_st12_fsm_11 => 
                ap_NS_fsm <= ap_ST_st13_fsm_12;
            when ap_ST_st13_fsm_12 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_uart_read_reg_fu_210_ap_done))) then
                    ap_NS_fsm <= ap_ST_st14_fsm_13;
                else
                    ap_NS_fsm <= ap_ST_st13_fsm_12;
                end if;
            when ap_ST_st14_fsm_13 => 
                ap_NS_fsm <= ap_ST_st15_fsm_14;
            when ap_ST_st15_fsm_14 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_uart_write_reg_fu_225_ap_done))) then
                    ap_NS_fsm <= ap_ST_st16_fsm_15;
                else
                    ap_NS_fsm <= ap_ST_st15_fsm_14;
                end if;
            when ap_ST_st16_fsm_15 => 
                ap_NS_fsm <= ap_ST_st17_fsm_16;
            when ap_ST_st17_fsm_16 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_wait_tmr_fu_244_ap_done))) then
                    ap_NS_fsm <= ap_ST_st18_fsm_17;
                else
                    ap_NS_fsm <= ap_ST_st17_fsm_16;
                end if;
            when ap_ST_st18_fsm_17 => 
                ap_NS_fsm <= ap_ST_st19_fsm_18;
            when ap_ST_st19_fsm_18 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_uart_read_reg_fu_210_ap_done))) then
                    ap_NS_fsm <= ap_ST_st20_fsm_19;
                else
                    ap_NS_fsm <= ap_ST_st19_fsm_18;
                end if;
            when ap_ST_st20_fsm_19 => 
                ap_NS_fsm <= ap_ST_st21_fsm_20;
            when ap_ST_st21_fsm_20 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_uart_write_reg_fu_225_ap_done))) then
                    ap_NS_fsm <= ap_ST_st22_fsm_21;
                else
                    ap_NS_fsm <= ap_ST_st21_fsm_20;
                end if;
            when ap_ST_st22_fsm_21 => 
                ap_NS_fsm <= ap_ST_st23_fsm_22;
            when ap_ST_st23_fsm_22 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_wait_tmr_fu_244_ap_done))) then
                    ap_NS_fsm <= ap_ST_st24_fsm_23;
                else
                    ap_NS_fsm <= ap_ST_st23_fsm_22;
                end if;
            when ap_ST_st24_fsm_23 => 
                ap_NS_fsm <= ap_ST_st25_fsm_24;
            when ap_ST_st25_fsm_24 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_uart_read_reg_fu_210_ap_done))) then
                    ap_NS_fsm <= ap_ST_st26_fsm_25;
                else
                    ap_NS_fsm <= ap_ST_st25_fsm_24;
                end if;
            when ap_ST_st26_fsm_25 => 
                ap_NS_fsm <= ap_ST_st27_fsm_26;
            when ap_ST_st27_fsm_26 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_uart_write_reg_fu_225_ap_done))) then
                    ap_NS_fsm <= ap_ST_st28_fsm_27;
                else
                    ap_NS_fsm <= ap_ST_st27_fsm_26;
                end if;
            when ap_ST_st28_fsm_27 => 
                ap_NS_fsm <= ap_ST_st29_fsm_28;
            when ap_ST_st29_fsm_28 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_wait_tmr_fu_244_ap_done))) then
                    ap_NS_fsm <= ap_ST_st30_fsm_29;
                else
                    ap_NS_fsm <= ap_ST_st29_fsm_28;
                end if;
            when ap_ST_st30_fsm_29 => 
                ap_NS_fsm <= ap_ST_st31_fsm_30;
            when ap_ST_st31_fsm_30 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_uart_read_reg_fu_210_ap_done))) then
                    ap_NS_fsm <= ap_ST_st32_fsm_31;
                else
                    ap_NS_fsm <= ap_ST_st31_fsm_30;
                end if;
            when ap_ST_st32_fsm_31 => 
                ap_NS_fsm <= ap_ST_st33_fsm_32;
            when ap_ST_st33_fsm_32 => 
                if (not(((ap_const_logic_0 = grp_bno055_uart_write_mem_fu_254_ap_done) or (ap_const_logic_0 = grp_bno055_uart_uart_read_reg16_fu_200_ap_done)))) then
                    ap_NS_fsm <= ap_ST_st34_fsm_33;
                else
                    ap_NS_fsm <= ap_ST_st33_fsm_32;
                end if;
            when ap_ST_st34_fsm_33 => 
                ap_NS_fsm <= ap_ST_st35_fsm_34;
            when ap_ST_st35_fsm_34 => 
                if (not(((ap_const_logic_0 = grp_bno055_uart_write_mem_fu_254_ap_done) or (ap_const_logic_0 = grp_bno055_uart_wait_tmr_fu_244_ap_done)))) then
                    ap_NS_fsm <= ap_ST_st36_fsm_35;
                else
                    ap_NS_fsm <= ap_ST_st35_fsm_34;
                end if;
            when ap_ST_st36_fsm_35 => 
                ap_NS_fsm <= ap_ST_st37_fsm_36;
            when ap_ST_st37_fsm_36 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_write_mem_fu_254_ap_done))) then
                    ap_NS_fsm <= ap_ST_st38_fsm_37;
                else
                    ap_NS_fsm <= ap_ST_st37_fsm_36;
                end if;
            when ap_ST_st38_fsm_37 => 
                ap_NS_fsm <= ap_ST_st39_fsm_38;
            when ap_ST_st39_fsm_38 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_write_mem_fu_254_ap_done))) then
                    ap_NS_fsm <= ap_ST_st40_fsm_39;
                else
                    ap_NS_fsm <= ap_ST_st39_fsm_38;
                end if;
            when ap_ST_st40_fsm_39 => 
                ap_NS_fsm <= ap_ST_st41_fsm_40;
            when ap_ST_st41_fsm_40 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_write_mem_fu_254_ap_done))) then
                    ap_NS_fsm <= ap_ST_st42_fsm_41;
                else
                    ap_NS_fsm <= ap_ST_st41_fsm_40;
                end if;
            when ap_ST_st42_fsm_41 => 
                ap_NS_fsm <= ap_ST_st43_fsm_42;
            when ap_ST_st43_fsm_42 => 
                if (not((ap_const_logic_0 = grp_bno055_uart_write_mem_fu_254_ap_done))) then
                    ap_NS_fsm <= ap_ST_st30_fsm_29;
                else
                    ap_NS_fsm <= ap_ST_st43_fsm_42;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_done <= ap_const_logic_0;

    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= ap_const_logic_0;

    ap_sig_353_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_353 <= (ap_const_lv1_1 = ap_CS_fsm(18 downto 18));
    end process;


    ap_sig_364_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_364 <= (ap_const_lv1_1 = ap_CS_fsm(30 downto 30));
    end process;


    ap_sig_375_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_375 <= (ap_const_lv1_1 = ap_CS_fsm(12 downto 12));
    end process;


    ap_sig_385_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_385 <= (ap_const_lv1_1 = ap_CS_fsm(13 downto 13));
    end process;


    ap_sig_394_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_394 <= (ap_const_lv1_1 = ap_CS_fsm(19 downto 19));
    end process;


    ap_sig_403_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_403 <= (ap_const_lv1_1 = ap_CS_fsm(24 downto 24));
    end process;


    ap_sig_413_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_413 <= (ap_const_lv1_1 = ap_CS_fsm(25 downto 25));
    end process;


    ap_sig_424_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_424 <= (ap_const_lv1_1 = ap_CS_fsm(31 downto 31));
    end process;


    ap_sig_433_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_433 <= (ap_const_lv1_1 = ap_CS_fsm(32 downto 32));
    end process;


    ap_sig_451_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_451 <= (ap_const_lv1_1 = ap_CS_fsm(33 downto 33));
    end process;


    ap_sig_460_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_460 <= (ap_const_lv1_1 = ap_CS_fsm(36 downto 36));
    end process;


    ap_sig_545_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_545 <= (ap_const_lv1_1 = ap_CS_fsm(11 downto 11));
    end process;


    ap_sig_552_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_552 <= (ap_const_lv1_1 = ap_CS_fsm(17 downto 17));
    end process;


    ap_sig_560_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_560 <= (ap_const_lv1_1 = ap_CS_fsm(23 downto 23));
    end process;


    ap_sig_568_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_568 <= (ap_const_lv1_1 = ap_CS_fsm(29 downto 29));
    end process;


    ap_sig_58_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_58 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    ap_sig_600_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_600 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    ap_sig_607_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_607 <= (ap_const_lv1_1 = ap_CS_fsm(5 downto 5));
    end process;


    ap_sig_615_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_615 <= (ap_const_lv1_1 = ap_CS_fsm(9 downto 9));
    end process;


    ap_sig_627_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_627 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    ap_sig_635_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_635 <= (ap_const_lv1_1 = ap_CS_fsm(6 downto 6));
    end process;


    ap_sig_642_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_642 <= (ap_const_lv1_1 = ap_CS_fsm(10 downto 10));
    end process;


    ap_sig_651_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_651 <= (ap_const_lv1_1 = ap_CS_fsm(14 downto 14));
    end process;


    ap_sig_659_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_659 <= (ap_const_lv1_1 = ap_CS_fsm(20 downto 20));
    end process;


    ap_sig_667_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_667 <= (ap_const_lv1_1 = ap_CS_fsm(26 downto 26));
    end process;


    ap_sig_706_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_706 <= (ap_const_lv1_1 = ap_CS_fsm(7 downto 7));
    end process;


    ap_sig_713_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_713 <= (ap_const_lv1_1 = ap_CS_fsm(15 downto 15));
    end process;


    ap_sig_721_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_721 <= (ap_const_lv1_1 = ap_CS_fsm(21 downto 21));
    end process;


    ap_sig_729_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_729 <= (ap_const_lv1_1 = ap_CS_fsm(27 downto 27));
    end process;


    ap_sig_739_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_739 <= (ap_const_lv1_1 = ap_CS_fsm(8 downto 8));
    end process;


    ap_sig_747_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_747 <= (ap_const_lv1_1 = ap_CS_fsm(16 downto 16));
    end process;


    ap_sig_754_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_754 <= (ap_const_lv1_1 = ap_CS_fsm(22 downto 22));
    end process;


    ap_sig_762_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_762 <= (ap_const_lv1_1 = ap_CS_fsm(28 downto 28));
    end process;


    ap_sig_771_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_771 <= (ap_const_lv1_1 = ap_CS_fsm(34 downto 34));
    end process;


    ap_sig_796_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_796 <= (ap_const_lv1_1 = ap_CS_fsm(35 downto 35));
    end process;


    ap_sig_804_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_804 <= (ap_const_lv1_1 = ap_CS_fsm(37 downto 37));
    end process;


    ap_sig_812_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_812 <= (ap_const_lv1_1 = ap_CS_fsm(39 downto 39));
    end process;


    ap_sig_820_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_820 <= (ap_const_lv1_1 = ap_CS_fsm(41 downto 41));
    end process;


    ap_sig_833_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_833 <= (ap_const_lv1_1 = ap_CS_fsm(38 downto 38));
    end process;


    ap_sig_841_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_841 <= (ap_const_lv1_1 = ap_CS_fsm(40 downto 40));
    end process;


    ap_sig_848_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_848 <= (ap_const_lv1_1 = ap_CS_fsm(42 downto 42));
    end process;


    ap_sig_912_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_912 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    ap_sig_cseq_ST_st10_fsm_9_assign_proc : process(ap_sig_615)
    begin
        if (ap_sig_615) then 
            ap_sig_cseq_ST_st10_fsm_9 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st10_fsm_9 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st11_fsm_10_assign_proc : process(ap_sig_642)
    begin
        if (ap_sig_642) then 
            ap_sig_cseq_ST_st11_fsm_10 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st11_fsm_10 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st12_fsm_11_assign_proc : process(ap_sig_545)
    begin
        if (ap_sig_545) then 
            ap_sig_cseq_ST_st12_fsm_11 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st12_fsm_11 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st13_fsm_12_assign_proc : process(ap_sig_375)
    begin
        if (ap_sig_375) then 
            ap_sig_cseq_ST_st13_fsm_12 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st13_fsm_12 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st14_fsm_13_assign_proc : process(ap_sig_385)
    begin
        if (ap_sig_385) then 
            ap_sig_cseq_ST_st14_fsm_13 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st14_fsm_13 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st15_fsm_14_assign_proc : process(ap_sig_651)
    begin
        if (ap_sig_651) then 
            ap_sig_cseq_ST_st15_fsm_14 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st15_fsm_14 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st16_fsm_15_assign_proc : process(ap_sig_713)
    begin
        if (ap_sig_713) then 
            ap_sig_cseq_ST_st16_fsm_15 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st16_fsm_15 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st17_fsm_16_assign_proc : process(ap_sig_747)
    begin
        if (ap_sig_747) then 
            ap_sig_cseq_ST_st17_fsm_16 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st17_fsm_16 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st18_fsm_17_assign_proc : process(ap_sig_552)
    begin
        if (ap_sig_552) then 
            ap_sig_cseq_ST_st18_fsm_17 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st18_fsm_17 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st19_fsm_18_assign_proc : process(ap_sig_353)
    begin
        if (ap_sig_353) then 
            ap_sig_cseq_ST_st19_fsm_18 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st19_fsm_18 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_58)
    begin
        if (ap_sig_58) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st20_fsm_19_assign_proc : process(ap_sig_394)
    begin
        if (ap_sig_394) then 
            ap_sig_cseq_ST_st20_fsm_19 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st20_fsm_19 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st21_fsm_20_assign_proc : process(ap_sig_659)
    begin
        if (ap_sig_659) then 
            ap_sig_cseq_ST_st21_fsm_20 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st21_fsm_20 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st22_fsm_21_assign_proc : process(ap_sig_721)
    begin
        if (ap_sig_721) then 
            ap_sig_cseq_ST_st22_fsm_21 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st22_fsm_21 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st23_fsm_22_assign_proc : process(ap_sig_754)
    begin
        if (ap_sig_754) then 
            ap_sig_cseq_ST_st23_fsm_22 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st23_fsm_22 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st24_fsm_23_assign_proc : process(ap_sig_560)
    begin
        if (ap_sig_560) then 
            ap_sig_cseq_ST_st24_fsm_23 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st24_fsm_23 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st25_fsm_24_assign_proc : process(ap_sig_403)
    begin
        if (ap_sig_403) then 
            ap_sig_cseq_ST_st25_fsm_24 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st25_fsm_24 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st26_fsm_25_assign_proc : process(ap_sig_413)
    begin
        if (ap_sig_413) then 
            ap_sig_cseq_ST_st26_fsm_25 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st26_fsm_25 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st27_fsm_26_assign_proc : process(ap_sig_667)
    begin
        if (ap_sig_667) then 
            ap_sig_cseq_ST_st27_fsm_26 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st27_fsm_26 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st28_fsm_27_assign_proc : process(ap_sig_729)
    begin
        if (ap_sig_729) then 
            ap_sig_cseq_ST_st28_fsm_27 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st28_fsm_27 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st29_fsm_28_assign_proc : process(ap_sig_762)
    begin
        if (ap_sig_762) then 
            ap_sig_cseq_ST_st29_fsm_28 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st29_fsm_28 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_912)
    begin
        if (ap_sig_912) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st30_fsm_29_assign_proc : process(ap_sig_568)
    begin
        if (ap_sig_568) then 
            ap_sig_cseq_ST_st30_fsm_29 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st30_fsm_29 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st31_fsm_30_assign_proc : process(ap_sig_364)
    begin
        if (ap_sig_364) then 
            ap_sig_cseq_ST_st31_fsm_30 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st31_fsm_30 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st32_fsm_31_assign_proc : process(ap_sig_424)
    begin
        if (ap_sig_424) then 
            ap_sig_cseq_ST_st32_fsm_31 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st32_fsm_31 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st33_fsm_32_assign_proc : process(ap_sig_433)
    begin
        if (ap_sig_433) then 
            ap_sig_cseq_ST_st33_fsm_32 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st33_fsm_32 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st34_fsm_33_assign_proc : process(ap_sig_451)
    begin
        if (ap_sig_451) then 
            ap_sig_cseq_ST_st34_fsm_33 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st34_fsm_33 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st35_fsm_34_assign_proc : process(ap_sig_771)
    begin
        if (ap_sig_771) then 
            ap_sig_cseq_ST_st35_fsm_34 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st35_fsm_34 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st36_fsm_35_assign_proc : process(ap_sig_796)
    begin
        if (ap_sig_796) then 
            ap_sig_cseq_ST_st36_fsm_35 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st36_fsm_35 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st37_fsm_36_assign_proc : process(ap_sig_460)
    begin
        if (ap_sig_460) then 
            ap_sig_cseq_ST_st37_fsm_36 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st37_fsm_36 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st38_fsm_37_assign_proc : process(ap_sig_804)
    begin
        if (ap_sig_804) then 
            ap_sig_cseq_ST_st38_fsm_37 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st38_fsm_37 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st39_fsm_38_assign_proc : process(ap_sig_833)
    begin
        if (ap_sig_833) then 
            ap_sig_cseq_ST_st39_fsm_38 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st39_fsm_38 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st40_fsm_39_assign_proc : process(ap_sig_812)
    begin
        if (ap_sig_812) then 
            ap_sig_cseq_ST_st40_fsm_39 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st40_fsm_39 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st41_fsm_40_assign_proc : process(ap_sig_841)
    begin
        if (ap_sig_841) then 
            ap_sig_cseq_ST_st41_fsm_40 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st41_fsm_40 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st42_fsm_41_assign_proc : process(ap_sig_820)
    begin
        if (ap_sig_820) then 
            ap_sig_cseq_ST_st42_fsm_41 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st42_fsm_41 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st43_fsm_42_assign_proc : process(ap_sig_848)
    begin
        if (ap_sig_848) then 
            ap_sig_cseq_ST_st43_fsm_42 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st43_fsm_42 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st4_fsm_3_assign_proc : process(ap_sig_600)
    begin
        if (ap_sig_600) then 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st5_fsm_4_assign_proc : process(ap_sig_627)
    begin
        if (ap_sig_627) then 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st6_fsm_5_assign_proc : process(ap_sig_607)
    begin
        if (ap_sig_607) then 
            ap_sig_cseq_ST_st6_fsm_5 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st6_fsm_5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st7_fsm_6_assign_proc : process(ap_sig_635)
    begin
        if (ap_sig_635) then 
            ap_sig_cseq_ST_st7_fsm_6 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st7_fsm_6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st8_fsm_7_assign_proc : process(ap_sig_706)
    begin
        if (ap_sig_706) then 
            ap_sig_cseq_ST_st8_fsm_7 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st8_fsm_7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st9_fsm_8_assign_proc : process(ap_sig_739)
    begin
        if (ap_sig_739) then 
            ap_sig_cseq_ST_st9_fsm_8 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st9_fsm_8 <= ap_const_logic_0;
        end if; 
    end process;

    dummy_tmr_out_0_ack_out <= ap_const_logic_0;

    dummy_tmr_out_1_data_in_assign_proc : process(ap_sig_cseq_ST_st19_fsm_18, ap_sig_cseq_ST_st31_fsm_30, ap_sig_cseq_ST_st13_fsm_12, ap_sig_cseq_ST_st25_fsm_24, ap_sig_cseq_ST_st33_fsm_32, grp_bno055_uart_uart_read_reg16_fu_200_dummy_tmr_out_o, grp_bno055_uart_uart_read_reg16_fu_200_dummy_tmr_out_o_ap_vld, grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o, grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o_ap_vld, grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o, grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o_ap_vld, grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o, grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o_ap_vld, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st7_fsm_6, ap_sig_cseq_ST_st11_fsm_10, ap_sig_cseq_ST_st15_fsm_14, ap_sig_cseq_ST_st21_fsm_20, ap_sig_cseq_ST_st27_fsm_26, ap_sig_cseq_ST_st9_fsm_8, ap_sig_cseq_ST_st17_fsm_16, ap_sig_cseq_ST_st23_fsm_22, ap_sig_cseq_ST_st29_fsm_28, ap_sig_cseq_ST_st35_fsm_34)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st9_fsm_8) and (ap_const_logic_1 = grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st17_fsm_16) and (ap_const_logic_1 = grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st23_fsm_22) and (ap_const_logic_1 = grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st29_fsm_28) and (ap_const_logic_1 = grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st35_fsm_34) and (ap_const_logic_1 = grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o_ap_vld)))) then 
            dummy_tmr_out_1_data_in <= grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and (ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6) and (ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10) and (ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st15_fsm_14) and (ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st21_fsm_20) and (ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st27_fsm_26) and (ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o_ap_vld)))) then 
            dummy_tmr_out_1_data_in <= grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and (ap_const_logic_1 = grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st19_fsm_18) and (ap_const_logic_1 = grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st25_fsm_24) and (ap_const_logic_1 = grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st31_fsm_30) and (ap_const_logic_1 = grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o_ap_vld)))) then 
            dummy_tmr_out_1_data_in <= grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st33_fsm_32) and (ap_const_logic_1 = grp_bno055_uart_uart_read_reg16_fu_200_dummy_tmr_out_o_ap_vld))) then 
            dummy_tmr_out_1_data_in <= grp_bno055_uart_uart_read_reg16_fu_200_dummy_tmr_out_o;
        else 
            dummy_tmr_out_1_data_in <= "X";
        end if; 
    end process;


    dummy_tmr_out_1_vld_in_assign_proc : process(ap_sig_cseq_ST_st19_fsm_18, ap_sig_cseq_ST_st31_fsm_30, ap_sig_cseq_ST_st13_fsm_12, ap_sig_cseq_ST_st25_fsm_24, ap_sig_cseq_ST_st33_fsm_32, grp_bno055_uart_uart_read_reg16_fu_200_dummy_tmr_out_o_ap_vld, grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o_ap_vld, grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o_ap_vld, grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o_ap_vld, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st7_fsm_6, ap_sig_cseq_ST_st11_fsm_10, ap_sig_cseq_ST_st15_fsm_14, ap_sig_cseq_ST_st21_fsm_20, ap_sig_cseq_ST_st27_fsm_26, ap_sig_cseq_ST_st9_fsm_8, ap_sig_cseq_ST_st17_fsm_16, ap_sig_cseq_ST_st23_fsm_22, ap_sig_cseq_ST_st29_fsm_28, ap_sig_cseq_ST_st35_fsm_34)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st9_fsm_8) or (ap_const_logic_1 = ap_sig_cseq_ST_st17_fsm_16) or (ap_const_logic_1 = ap_sig_cseq_ST_st23_fsm_22) or (ap_const_logic_1 = ap_sig_cseq_ST_st29_fsm_28) or (ap_const_logic_1 = ap_sig_cseq_ST_st35_fsm_34))) then 
            dummy_tmr_out_1_vld_in <= grp_bno055_uart_wait_tmr_fu_244_dummy_tmr_out_o_ap_vld;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) or (ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6) or (ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10) or (ap_const_logic_1 = ap_sig_cseq_ST_st15_fsm_14) or (ap_const_logic_1 = ap_sig_cseq_ST_st21_fsm_20) or (ap_const_logic_1 = ap_sig_cseq_ST_st27_fsm_26))) then 
            dummy_tmr_out_1_vld_in <= grp_bno055_uart_uart_write_reg_fu_225_dummy_tmr_out_o_ap_vld;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st19_fsm_18) or (ap_const_logic_1 = ap_sig_cseq_ST_st31_fsm_30) or (ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) or (ap_const_logic_1 = ap_sig_cseq_ST_st25_fsm_24))) then 
            dummy_tmr_out_1_vld_in <= grp_bno055_uart_uart_read_reg_fu_210_dummy_tmr_out_o_ap_vld;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st33_fsm_32)) then 
            dummy_tmr_out_1_vld_in <= grp_bno055_uart_uart_read_reg16_fu_200_dummy_tmr_out_o_ap_vld;
        else 
            dummy_tmr_out_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    dummy_tmr_out_o <= dummy_tmr_out_1_data_reg;
    e_1_fu_392_p0 <= ap_const_lv20_64(8 - 1 downto 0);
    e_1_fu_392_p1 <= e_1_fu_392_p10(16 - 1 downto 0);
    e_1_fu_392_p10 <= std_logic_vector(resize(unsigned(e_fu_364_p3),20));
    e_fu_364_p3 <= (tmp_11_reg_435 & e_tmp_1_reg_440);

    grp_bno055_uart_bin2char_fu_277_val_r_assign_proc : process(reg_292, tmp_10_reg_425, ap_sig_cseq_ST_st32_fsm_31, ap_sig_cseq_ST_st34_fsm_33)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st34_fsm_33)) then 
            grp_bno055_uart_bin2char_fu_277_val_r <= tmp_10_reg_425;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st32_fsm_31)) then 
            grp_bno055_uart_bin2char_fu_277_val_r <= reg_292;
        else 
            grp_bno055_uart_bin2char_fu_277_val_r <= "XXXX";
        end if; 
    end process;

    grp_bno055_uart_uart_read_reg16_fu_200_ap_start <= ap_reg_grp_bno055_uart_uart_read_reg16_fu_200_ap_start;
    grp_bno055_uart_uart_read_reg_fu_210_ap_start <= ap_reg_grp_bno055_uart_uart_read_reg_fu_210_ap_start;

    grp_bno055_uart_uart_read_reg_fu_210_reg_addr_assign_proc : process(ap_sig_cseq_ST_st19_fsm_18, ap_sig_cseq_ST_st31_fsm_30, ap_sig_cseq_ST_st13_fsm_12, ap_sig_cseq_ST_st25_fsm_24)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st31_fsm_30)) then 
            grp_bno055_uart_uart_read_reg_fu_210_reg_addr <= ap_const_lv8_0;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st25_fsm_24)) then 
            grp_bno055_uart_uart_read_reg_fu_210_reg_addr <= ap_const_lv8_3B;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st19_fsm_18)) then 
            grp_bno055_uart_uart_read_reg_fu_210_reg_addr <= ap_const_lv8_3D;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12)) then 
            grp_bno055_uart_uart_read_reg_fu_210_reg_addr <= ap_const_lv8_3E;
        else 
            grp_bno055_uart_uart_read_reg_fu_210_reg_addr <= "XXXXXXXX";
        end if; 
    end process;

    grp_bno055_uart_uart_write_reg_fu_225_ap_start <= ap_reg_grp_bno055_uart_uart_write_reg_fu_225_ap_start;

    grp_bno055_uart_uart_write_reg_fu_225_data_assign_proc : process(tmp_s_reg_405, tmp_4_reg_410, tmp_5_reg_420, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st7_fsm_6, ap_sig_cseq_ST_st11_fsm_10, ap_sig_cseq_ST_st15_fsm_14, ap_sig_cseq_ST_st21_fsm_20, ap_sig_cseq_ST_st27_fsm_26)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st27_fsm_26)) then 
            grp_bno055_uart_uart_write_reg_fu_225_data <= tmp_5_reg_420;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st21_fsm_20)) then 
            grp_bno055_uart_uart_write_reg_fu_225_data <= tmp_4_reg_410;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st15_fsm_14)) then 
            grp_bno055_uart_uart_write_reg_fu_225_data <= tmp_s_reg_405;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6)) then 
            grp_bno055_uart_uart_write_reg_fu_225_data <= ap_const_lv8_C0;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) or (ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10))) then 
            grp_bno055_uart_uart_write_reg_fu_225_data <= ap_const_lv8_0;
        else 
            grp_bno055_uart_uart_write_reg_fu_225_data <= "XXXXXXXX";
        end if; 
    end process;


    grp_bno055_uart_uart_write_reg_fu_225_reg_addr_assign_proc : process(ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st7_fsm_6, ap_sig_cseq_ST_st11_fsm_10, ap_sig_cseq_ST_st15_fsm_14, ap_sig_cseq_ST_st21_fsm_20, ap_sig_cseq_ST_st27_fsm_26)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st27_fsm_26)) then 
            grp_bno055_uart_uart_write_reg_fu_225_reg_addr <= ap_const_lv7_3B;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st21_fsm_20)) then 
            grp_bno055_uart_uart_write_reg_fu_225_reg_addr <= ap_const_lv7_3D;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st15_fsm_14)) then 
            grp_bno055_uart_uart_write_reg_fu_225_reg_addr <= ap_const_lv7_3E;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6)) then 
            grp_bno055_uart_uart_write_reg_fu_225_reg_addr <= ap_const_lv7_3F;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) or (ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10))) then 
            grp_bno055_uart_uart_write_reg_fu_225_reg_addr <= ap_const_lv7_7;
        else 
            grp_bno055_uart_uart_write_reg_fu_225_reg_addr <= "XXXXXXX";
        end if; 
    end process;

    grp_bno055_uart_wait_tmr_fu_244_ap_start <= ap_reg_grp_bno055_uart_wait_tmr_fu_244_ap_start;

    grp_bno055_uart_wait_tmr_fu_244_tmr_assign_proc : process(ap_sig_cseq_ST_st9_fsm_8, ap_sig_cseq_ST_st17_fsm_16, ap_sig_cseq_ST_st23_fsm_22, ap_sig_cseq_ST_st29_fsm_28, ap_sig_cseq_ST_st35_fsm_34)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st35_fsm_34)) then 
            grp_bno055_uart_wait_tmr_fu_244_tmr <= ap_const_lv28_F4240;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st17_fsm_16) or (ap_const_logic_1 = ap_sig_cseq_ST_st29_fsm_28))) then 
            grp_bno055_uart_wait_tmr_fu_244_tmr <= ap_const_lv28_989680;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st9_fsm_8) or (ap_const_logic_1 = ap_sig_cseq_ST_st23_fsm_22))) then 
            grp_bno055_uart_wait_tmr_fu_244_tmr <= ap_const_lv28_5F5E100;
        else 
            grp_bno055_uart_wait_tmr_fu_244_tmr <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_bno055_uart_write_mem_fu_254_addr_assign_proc : process(ap_sig_cseq_ST_st33_fsm_32, ap_sig_cseq_ST_st37_fsm_36, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st7_fsm_6, ap_sig_cseq_ST_st35_fsm_34, ap_sig_cseq_ST_st39_fsm_38, ap_sig_cseq_ST_st41_fsm_40, ap_sig_cseq_ST_st43_fsm_42)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st41_fsm_40)) then 
            grp_bno055_uart_write_mem_fu_254_addr <= ap_const_lv8_84;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st39_fsm_38)) then 
            grp_bno055_uart_write_mem_fu_254_addr <= ap_const_lv8_83;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st37_fsm_36) or (ap_const_logic_1 = ap_sig_cseq_ST_st43_fsm_42))) then 
            grp_bno055_uart_write_mem_fu_254_addr <= ap_const_lv8_85;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st35_fsm_34)) then 
            grp_bno055_uart_write_mem_fu_254_addr <= ap_const_lv8_1;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st33_fsm_32)) then 
            grp_bno055_uart_write_mem_fu_254_addr <= ap_const_lv8_0;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6)) then 
            grp_bno055_uart_write_mem_fu_254_addr <= ap_const_lv8_16;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then 
            grp_bno055_uart_write_mem_fu_254_addr <= ap_const_lv8_15;
        else 
            grp_bno055_uart_write_mem_fu_254_addr <= "XXXXXXXX";
        end if; 
    end process;

    grp_bno055_uart_write_mem_fu_254_ap_start <= ap_reg_grp_bno055_uart_write_mem_fu_254_ap_start;

    grp_bno055_uart_write_mem_fu_254_data_assign_proc : process(p_trunc_ext_reg_430, ap_sig_cseq_ST_st33_fsm_32, p_trunc2_ext_reg_445, tmp_2_reg_450, ap_sig_cseq_ST_st37_fsm_36, tmp_6_reg_455, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st7_fsm_6, ap_sig_cseq_ST_st35_fsm_34, ap_sig_cseq_ST_st39_fsm_38, ap_sig_cseq_ST_st41_fsm_40, ap_sig_cseq_ST_st43_fsm_42)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st43_fsm_42)) then 
            grp_bno055_uart_write_mem_fu_254_data <= ap_const_lv8_1;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st41_fsm_40)) then 
            grp_bno055_uart_write_mem_fu_254_data <= tmp_6_reg_455;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st39_fsm_38)) then 
            grp_bno055_uart_write_mem_fu_254_data <= tmp_2_reg_450;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st35_fsm_34)) then 
            grp_bno055_uart_write_mem_fu_254_data <= p_trunc2_ext_reg_445;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st33_fsm_32)) then 
            grp_bno055_uart_write_mem_fu_254_data <= p_trunc_ext_reg_430;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st37_fsm_36) or (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) or (ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6))) then 
            grp_bno055_uart_write_mem_fu_254_data <= ap_const_lv8_0;
        else 
            grp_bno055_uart_write_mem_fu_254_data <= "XXXXXXXX";
        end if; 
    end process;


    mem_addr_1_vld_in_assign_proc : process(ap_sig_cseq_ST_st33_fsm_32, ap_sig_cseq_ST_st37_fsm_36, grp_bno055_uart_write_mem_fu_254_mem_addr_ap_vld, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st7_fsm_6, ap_sig_cseq_ST_st35_fsm_34, ap_sig_cseq_ST_st39_fsm_38, ap_sig_cseq_ST_st41_fsm_40, ap_sig_cseq_ST_st43_fsm_42)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st33_fsm_32) or (ap_const_logic_1 = ap_sig_cseq_ST_st37_fsm_36) or (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) or (ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6) or (ap_const_logic_1 = ap_sig_cseq_ST_st35_fsm_34) or (ap_const_logic_1 = ap_sig_cseq_ST_st39_fsm_38) or (ap_const_logic_1 = ap_sig_cseq_ST_st41_fsm_40) or (ap_const_logic_1 = ap_sig_cseq_ST_st43_fsm_42))) then 
            mem_addr_1_vld_in <= grp_bno055_uart_write_mem_fu_254_mem_addr_ap_vld;
        else 
            mem_addr_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    mem_addr_o <= mem_addr_1_data_reg;

    mem_dout_1_vld_in_assign_proc : process(ap_sig_cseq_ST_st33_fsm_32, ap_sig_cseq_ST_st37_fsm_36, grp_bno055_uart_write_mem_fu_254_mem_dout_ap_vld, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st7_fsm_6, ap_sig_cseq_ST_st35_fsm_34, ap_sig_cseq_ST_st39_fsm_38, ap_sig_cseq_ST_st41_fsm_40, ap_sig_cseq_ST_st43_fsm_42)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st33_fsm_32) or (ap_const_logic_1 = ap_sig_cseq_ST_st37_fsm_36) or (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) or (ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6) or (ap_const_logic_1 = ap_sig_cseq_ST_st35_fsm_34) or (ap_const_logic_1 = ap_sig_cseq_ST_st39_fsm_38) or (ap_const_logic_1 = ap_sig_cseq_ST_st41_fsm_40) or (ap_const_logic_1 = ap_sig_cseq_ST_st43_fsm_42))) then 
            mem_dout_1_vld_in <= grp_bno055_uart_write_mem_fu_254_mem_dout_ap_vld;
        else 
            mem_dout_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    mem_dout_o <= mem_dout_1_data_reg;

    mem_wreq_1_vld_in_assign_proc : process(ap_sig_cseq_ST_st33_fsm_32, ap_sig_cseq_ST_st37_fsm_36, grp_bno055_uart_write_mem_fu_254_mem_wreq_ap_vld, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st7_fsm_6, ap_sig_cseq_ST_st35_fsm_34, ap_sig_cseq_ST_st39_fsm_38, ap_sig_cseq_ST_st41_fsm_40, ap_sig_cseq_ST_st43_fsm_42)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st33_fsm_32) or (ap_const_logic_1 = ap_sig_cseq_ST_st37_fsm_36) or (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) or (ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6) or (ap_const_logic_1 = ap_sig_cseq_ST_st35_fsm_34) or (ap_const_logic_1 = ap_sig_cseq_ST_st39_fsm_38) or (ap_const_logic_1 = ap_sig_cseq_ST_st41_fsm_40) or (ap_const_logic_1 = ap_sig_cseq_ST_st43_fsm_42))) then 
            mem_wreq_1_vld_in <= grp_bno055_uart_write_mem_fu_254_mem_wreq_ap_vld;
        else 
            mem_wreq_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    mem_wreq_o <= mem_wreq_1_data_reg;
    p_trunc2_ext_fu_359_p1 <= std_logic_vector(resize(unsigned(grp_bno055_uart_bin2char_fu_277_ap_return),8));
    p_trunc_ext_fu_340_p1 <= std_logic_vector(resize(unsigned(grp_bno055_uart_bin2char_fu_277_ap_return),8));
    tmp_10_fu_336_p1 <= grp_bno055_uart_uart_read_reg_fu_210_ap_return(4 - 1 downto 0);
    tmp_11_fu_345_p1 <= grp_bno055_uart_uart_read_reg16_fu_200_ap_return(8 - 1 downto 0);
    tmp_3_fu_315_p3 <= (reg_292 & ap_const_lv4_0);
    tmp_4_fu_323_p2 <= (tmp_3_fu_315_p3 or ap_const_lv8_C);
    tmp_5_fu_330_p2 <= (dt_2_reg_415 or ap_const_lv8_80);
    tmp_s_fu_307_p3 <= (tmp_reg_400 & ap_const_lv2_0);

    uart_tx_1_data_in_assign_proc : process(ap_sig_cseq_ST_st19_fsm_18, ap_sig_cseq_ST_st31_fsm_30, ap_sig_cseq_ST_st13_fsm_12, ap_sig_cseq_ST_st25_fsm_24, ap_sig_cseq_ST_st33_fsm_32, grp_bno055_uart_uart_read_reg16_fu_200_uart_tx, grp_bno055_uart_uart_read_reg16_fu_200_uart_tx_ap_vld, grp_bno055_uart_uart_read_reg_fu_210_uart_tx, grp_bno055_uart_uart_read_reg_fu_210_uart_tx_ap_vld, grp_bno055_uart_uart_write_reg_fu_225_uart_tx, grp_bno055_uart_uart_write_reg_fu_225_uart_tx_ap_vld, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st7_fsm_6, ap_sig_cseq_ST_st11_fsm_10, ap_sig_cseq_ST_st15_fsm_14, ap_sig_cseq_ST_st21_fsm_20, ap_sig_cseq_ST_st27_fsm_26, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
            uart_tx_1_data_in <= ap_const_lv1_1;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) and (ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_uart_tx_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6) and (ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_uart_tx_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10) and (ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_uart_tx_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st15_fsm_14) and (ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_uart_tx_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st21_fsm_20) and (ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_uart_tx_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st27_fsm_26) and (ap_const_logic_1 = grp_bno055_uart_uart_write_reg_fu_225_uart_tx_ap_vld)))) then 
            uart_tx_1_data_in <= grp_bno055_uart_uart_write_reg_fu_225_uart_tx;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) and (ap_const_logic_1 = grp_bno055_uart_uart_read_reg_fu_210_uart_tx_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st19_fsm_18) and (ap_const_logic_1 = grp_bno055_uart_uart_read_reg_fu_210_uart_tx_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st25_fsm_24) and (ap_const_logic_1 = grp_bno055_uart_uart_read_reg_fu_210_uart_tx_ap_vld)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st31_fsm_30) and (ap_const_logic_1 = grp_bno055_uart_uart_read_reg_fu_210_uart_tx_ap_vld)))) then 
            uart_tx_1_data_in <= grp_bno055_uart_uart_read_reg_fu_210_uart_tx;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st33_fsm_32) and (ap_const_logic_1 = grp_bno055_uart_uart_read_reg16_fu_200_uart_tx_ap_vld))) then 
            uart_tx_1_data_in <= grp_bno055_uart_uart_read_reg16_fu_200_uart_tx;
        else 
            uart_tx_1_data_in <= "X";
        end if; 
    end process;


    uart_tx_1_vld_in_assign_proc : process(ap_sig_cseq_ST_st19_fsm_18, ap_sig_cseq_ST_st31_fsm_30, ap_sig_cseq_ST_st13_fsm_12, ap_sig_cseq_ST_st25_fsm_24, ap_sig_cseq_ST_st33_fsm_32, grp_bno055_uart_uart_read_reg16_fu_200_uart_tx_ap_vld, grp_bno055_uart_uart_read_reg_fu_210_uart_tx_ap_vld, grp_bno055_uart_uart_write_reg_fu_225_uart_tx_ap_vld, ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st7_fsm_6, ap_sig_cseq_ST_st11_fsm_10, ap_sig_cseq_ST_st15_fsm_14, ap_sig_cseq_ST_st21_fsm_20, ap_sig_cseq_ST_st27_fsm_26, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
            uart_tx_1_vld_in <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) or (ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6) or (ap_const_logic_1 = ap_sig_cseq_ST_st11_fsm_10) or (ap_const_logic_1 = ap_sig_cseq_ST_st15_fsm_14) or (ap_const_logic_1 = ap_sig_cseq_ST_st21_fsm_20) or (ap_const_logic_1 = ap_sig_cseq_ST_st27_fsm_26))) then 
            uart_tx_1_vld_in <= grp_bno055_uart_uart_write_reg_fu_225_uart_tx_ap_vld;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st19_fsm_18) or (ap_const_logic_1 = ap_sig_cseq_ST_st31_fsm_30) or (ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_12) or (ap_const_logic_1 = ap_sig_cseq_ST_st25_fsm_24))) then 
            uart_tx_1_vld_in <= grp_bno055_uart_uart_read_reg_fu_210_uart_tx_ap_vld;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st33_fsm_32)) then 
            uart_tx_1_vld_in <= grp_bno055_uart_uart_read_reg16_fu_200_uart_tx_ap_vld;
        else 
            uart_tx_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    uart_tx_o <= uart_tx_1_data_reg;
end behav;
