// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module motor_ctrl_bin2char (
        val_r,
        ap_return
);

parameter    ap_const_lv7_46 = 7'b1000110;
parameter    ap_const_lv4_F = 4'b1111;
parameter    ap_const_lv7_45 = 7'b1000101;
parameter    ap_const_lv4_E = 4'b1110;
parameter    ap_const_lv7_44 = 7'b1000100;
parameter    ap_const_lv4_D = 4'b1101;
parameter    ap_const_lv7_43 = 7'b1000011;
parameter    ap_const_lv4_C = 4'b1100;
parameter    ap_const_lv7_42 = 7'b1000010;
parameter    ap_const_lv4_B = 4'b1011;
parameter    ap_const_lv7_41 = 7'b1000001;
parameter    ap_const_lv4_A = 4'b1010;
parameter    ap_const_lv7_39 = 7'b111001;
parameter    ap_const_lv4_9 = 4'b1001;
parameter    ap_const_lv7_38 = 7'b111000;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv7_37 = 7'b110111;
parameter    ap_const_lv4_7 = 4'b111;
parameter    ap_const_lv7_36 = 7'b110110;
parameter    ap_const_lv4_6 = 4'b110;
parameter    ap_const_lv7_35 = 7'b110101;
parameter    ap_const_lv4_5 = 4'b101;
parameter    ap_const_lv7_34 = 7'b110100;
parameter    ap_const_lv4_4 = 4'b100;
parameter    ap_const_lv7_33 = 7'b110011;
parameter    ap_const_lv4_3 = 4'b11;
parameter    ap_const_lv7_32 = 7'b110010;
parameter    ap_const_lv4_2 = 4'b10;
parameter    ap_const_lv7_31 = 7'b110001;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv7_30 = 7'b110000;
parameter    ap_const_lv4_0 = 4'b0000;

input  [3:0] val_r;
output  [6:0] ap_return;

reg   [6:0] retval_phi_fu_75_p32;
wire   [3:0] val_read_read_fu_66_p2;

always @ (*) begin
    if ((val_read_read_fu_66_p2 == ap_const_lv4_0)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_30;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_1)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_31;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_2)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_32;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_3)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_33;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_4)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_34;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_5)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_35;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_6)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_36;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_7)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_37;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_8)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_38;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_9)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_39;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_A)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_41;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_B)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_42;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_C)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_43;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_D)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_44;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_E)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_45;
    end else if ((val_read_read_fu_66_p2 == ap_const_lv4_F)) begin
        retval_phi_fu_75_p32 = ap_const_lv7_46;
    end else begin
        retval_phi_fu_75_p32 = 'bx;
    end
end

assign ap_return = retval_phi_fu_75_p32;

assign val_read_read_fu_66_p2 = val_r;

endmodule //motor_ctrl_bin2char
