// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _bno055_uart_uart_read_reg_HH_
#define _bno055_uart_uart_read_reg_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "bno055_uart_uart_receive_byte.h"
#include "bno055_uart_uart_send_byte.h"
#include "bno055_uart_wait_tmr.h"

namespace ap_rtl {

struct bno055_uart_uart_read_reg : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > reg_addr;
    sc_out< sc_lv<1> > uart_tx;
    sc_out< sc_logic > uart_tx_ap_vld;
    sc_in< sc_lv<1> > dummy_tmr_out_i;
    sc_out< sc_lv<1> > dummy_tmr_out_o;
    sc_out< sc_logic > dummy_tmr_out_o_ap_vld;
    sc_in< sc_lv<1> > uart_rx;
    sc_out< sc_lv<8> > ap_return;
    sc_signal< sc_lv<28> > ap_var_for_const0;


    // Module declarations
    bno055_uart_uart_read_reg(sc_module_name name);
    SC_HAS_PROCESS(bno055_uart_uart_read_reg);

    ~bno055_uart_uart_read_reg();

    sc_trace_file* mVcdFile;

    bno055_uart_uart_receive_byte* grp_bno055_uart_uart_receive_byte_fu_47;
    bno055_uart_uart_send_byte* grp_bno055_uart_uart_send_byte_fu_56;
    bno055_uart_wait_tmr* grp_bno055_uart_wait_tmr_fu_68;
    sc_signal< sc_lv<18> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_35;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_55;
    sc_signal< sc_lv<8> > grp_bno055_uart_uart_receive_byte_fu_47_ap_return;
    sc_signal< sc_logic > ap_sig_cseq_ST_st12_fsm_11;
    sc_signal< bool > ap_sig_64;
    sc_signal< sc_logic > grp_bno055_uart_uart_receive_byte_fu_47_ap_done;
    sc_signal< sc_lv<1> > tmp_fu_76_p2;
    sc_signal< sc_lv<1> > tmp_reg_98;
    sc_signal< sc_logic > ap_sig_cseq_ST_st14_fsm_13;
    sc_signal< bool > ap_sig_78;
    sc_signal< sc_logic > grp_bno055_uart_uart_receive_byte_fu_47_ap_start;
    sc_signal< sc_logic > grp_bno055_uart_uart_receive_byte_fu_47_ap_idle;
    sc_signal< sc_logic > grp_bno055_uart_uart_receive_byte_fu_47_ap_ready;
    sc_signal< sc_lv<1> > grp_bno055_uart_uart_receive_byte_fu_47_dummy_tmr_out_o;
    sc_signal< sc_logic > grp_bno055_uart_uart_receive_byte_fu_47_dummy_tmr_out_o_ap_vld;
    sc_signal< sc_logic > grp_bno055_uart_uart_send_byte_fu_56_ap_start;
    sc_signal< sc_logic > grp_bno055_uart_uart_send_byte_fu_56_ap_done;
    sc_signal< sc_logic > grp_bno055_uart_uart_send_byte_fu_56_ap_idle;
    sc_signal< sc_logic > grp_bno055_uart_uart_send_byte_fu_56_ap_ready;
    sc_signal< sc_lv<8> > grp_bno055_uart_uart_send_byte_fu_56_data;
    sc_signal< sc_lv<1> > grp_bno055_uart_uart_send_byte_fu_56_uart_tx;
    sc_signal< sc_logic > grp_bno055_uart_uart_send_byte_fu_56_uart_tx_ap_vld;
    sc_signal< sc_lv<1> > grp_bno055_uart_uart_send_byte_fu_56_dummy_tmr_out_o;
    sc_signal< sc_logic > grp_bno055_uart_uart_send_byte_fu_56_dummy_tmr_out_o_ap_vld;
    sc_signal< sc_logic > grp_bno055_uart_wait_tmr_fu_68_ap_start;
    sc_signal< sc_logic > grp_bno055_uart_wait_tmr_fu_68_ap_done;
    sc_signal< sc_logic > grp_bno055_uart_wait_tmr_fu_68_ap_idle;
    sc_signal< sc_logic > grp_bno055_uart_wait_tmr_fu_68_ap_ready;
    sc_signal< sc_lv<1> > grp_bno055_uart_wait_tmr_fu_68_dummy_tmr_out_o;
    sc_signal< sc_logic > grp_bno055_uart_wait_tmr_fu_68_dummy_tmr_out_o_ap_vld;
    sc_signal< sc_lv<8> > p_0_phi_fu_39_p6;
    sc_signal< sc_lv<8> > p_0_reg_36;
    sc_signal< sc_logic > ap_sig_cseq_ST_st18_fsm_17;
    sc_signal< bool > ap_sig_119;
    sc_signal< sc_lv<1> > tmp_s_fu_82_p2;
    sc_signal< sc_logic > ap_reg_grp_bno055_uart_uart_receive_byte_fu_47_ap_start;
    sc_signal< sc_logic > ap_sig_cseq_ST_st11_fsm_10;
    sc_signal< bool > ap_sig_143;
    sc_signal< sc_logic > ap_sig_cseq_ST_st13_fsm_12;
    sc_signal< bool > ap_sig_150;
    sc_signal< sc_logic > ap_sig_cseq_ST_st15_fsm_14;
    sc_signal< bool > ap_sig_158;
    sc_signal< sc_logic > ap_sig_cseq_ST_st17_fsm_16;
    sc_signal< bool > ap_sig_166;
    sc_signal< sc_logic > ap_sig_cseq_ST_st16_fsm_15;
    sc_signal< bool > ap_sig_175;
    sc_signal< sc_logic > ap_reg_grp_bno055_uart_uart_send_byte_fu_56_ap_start;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_197;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_206;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_215;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_223;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_230;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_237;
    sc_signal< sc_logic > ap_reg_grp_bno055_uart_wait_tmr_fu_68_ap_start;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_266;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_274;
    sc_signal< sc_lv<8> > ap_return_preg;
    sc_signal< sc_lv<18> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<18> ap_ST_st1_fsm_0;
    static const sc_lv<18> ap_ST_st2_fsm_1;
    static const sc_lv<18> ap_ST_st3_fsm_2;
    static const sc_lv<18> ap_ST_st4_fsm_3;
    static const sc_lv<18> ap_ST_st5_fsm_4;
    static const sc_lv<18> ap_ST_st6_fsm_5;
    static const sc_lv<18> ap_ST_st7_fsm_6;
    static const sc_lv<18> ap_ST_st8_fsm_7;
    static const sc_lv<18> ap_ST_st9_fsm_8;
    static const sc_lv<18> ap_ST_st10_fsm_9;
    static const sc_lv<18> ap_ST_st11_fsm_10;
    static const sc_lv<18> ap_ST_st12_fsm_11;
    static const sc_lv<18> ap_ST_st13_fsm_12;
    static const sc_lv<18> ap_ST_st14_fsm_13;
    static const sc_lv<18> ap_ST_st15_fsm_14;
    static const sc_lv<18> ap_ST_st16_fsm_15;
    static const sc_lv<18> ap_ST_st17_fsm_16;
    static const sc_lv<18> ap_ST_st18_fsm_17;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<8> ap_const_lv8_AA;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<28> ap_const_lv28_1;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<8> ap_const_lv8_BB;
    static const sc_lv<8> ap_const_lv8_EE;
    static const sc_lv<8> ap_const_lv8_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_ap_sig_119();
    void thread_ap_sig_143();
    void thread_ap_sig_150();
    void thread_ap_sig_158();
    void thread_ap_sig_166();
    void thread_ap_sig_175();
    void thread_ap_sig_197();
    void thread_ap_sig_206();
    void thread_ap_sig_215();
    void thread_ap_sig_223();
    void thread_ap_sig_230();
    void thread_ap_sig_237();
    void thread_ap_sig_266();
    void thread_ap_sig_274();
    void thread_ap_sig_35();
    void thread_ap_sig_55();
    void thread_ap_sig_64();
    void thread_ap_sig_78();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st11_fsm_10();
    void thread_ap_sig_cseq_ST_st12_fsm_11();
    void thread_ap_sig_cseq_ST_st13_fsm_12();
    void thread_ap_sig_cseq_ST_st14_fsm_13();
    void thread_ap_sig_cseq_ST_st15_fsm_14();
    void thread_ap_sig_cseq_ST_st16_fsm_15();
    void thread_ap_sig_cseq_ST_st17_fsm_16();
    void thread_ap_sig_cseq_ST_st18_fsm_17();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_dummy_tmr_out_o();
    void thread_dummy_tmr_out_o_ap_vld();
    void thread_grp_bno055_uart_uart_receive_byte_fu_47_ap_start();
    void thread_grp_bno055_uart_uart_send_byte_fu_56_ap_start();
    void thread_grp_bno055_uart_uart_send_byte_fu_56_data();
    void thread_grp_bno055_uart_wait_tmr_fu_68_ap_start();
    void thread_p_0_phi_fu_39_p6();
    void thread_tmp_fu_76_p2();
    void thread_tmp_s_fu_82_p2();
    void thread_uart_tx();
    void thread_uart_tx_ap_vld();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
