// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _bno055_uart_uart_write_reg_HH_
#define _bno055_uart_uart_write_reg_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "bno055_uart_uart_receive_byte.h"
#include "bno055_uart_uart_send_byte.h"
#include "bno055_uart_wait_tmr.h"

namespace ap_rtl {

struct bno055_uart_uart_write_reg : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<7> > reg_addr;
    sc_in< sc_lv<8> > data;
    sc_out< sc_lv<1> > uart_tx;
    sc_out< sc_logic > uart_tx_ap_vld;
    sc_in< sc_lv<1> > dummy_tmr_out_i;
    sc_out< sc_lv<1> > dummy_tmr_out_o;
    sc_out< sc_logic > dummy_tmr_out_o_ap_vld;
    sc_in< sc_lv<1> > uart_rx;
    sc_signal< sc_lv<28> > ap_var_for_const0;


    // Module declarations
    bno055_uart_uart_write_reg(sc_module_name name);
    SC_HAS_PROCESS(bno055_uart_uart_write_reg);

    ~bno055_uart_uart_write_reg();

    sc_trace_file* mVcdFile;

    bno055_uart_uart_receive_byte* grp_bno055_uart_uart_receive_byte_fu_44;
    bno055_uart_uart_send_byte* grp_bno055_uart_uart_send_byte_fu_52;
    bno055_uart_wait_tmr* grp_bno055_uart_wait_tmr_fu_64;
    sc_signal< sc_lv<16> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_33;
    sc_signal< sc_lv<8> > reg_addr_cast_fu_72_p1;
    sc_signal< sc_lv<8> > reg_addr_cast_reg_77;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_53;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_62;
    sc_signal< sc_logic > grp_bno055_uart_uart_send_byte_fu_52_ap_done;
    sc_signal< sc_logic > grp_bno055_uart_uart_receive_byte_fu_44_ap_start;
    sc_signal< sc_logic > grp_bno055_uart_uart_receive_byte_fu_44_ap_done;
    sc_signal< sc_logic > grp_bno055_uart_uart_receive_byte_fu_44_ap_idle;
    sc_signal< sc_logic > grp_bno055_uart_uart_receive_byte_fu_44_ap_ready;
    sc_signal< sc_lv<1> > grp_bno055_uart_uart_receive_byte_fu_44_dummy_tmr_out_o;
    sc_signal< sc_logic > grp_bno055_uart_uart_receive_byte_fu_44_dummy_tmr_out_o_ap_vld;
    sc_signal< sc_lv<8> > grp_bno055_uart_uart_receive_byte_fu_44_ap_return;
    sc_signal< sc_logic > grp_bno055_uart_uart_send_byte_fu_52_ap_start;
    sc_signal< sc_logic > grp_bno055_uart_uart_send_byte_fu_52_ap_idle;
    sc_signal< sc_logic > grp_bno055_uart_uart_send_byte_fu_52_ap_ready;
    sc_signal< sc_lv<8> > grp_bno055_uart_uart_send_byte_fu_52_data;
    sc_signal< sc_lv<1> > grp_bno055_uart_uart_send_byte_fu_52_uart_tx;
    sc_signal< sc_logic > grp_bno055_uart_uart_send_byte_fu_52_uart_tx_ap_vld;
    sc_signal< sc_lv<1> > grp_bno055_uart_uart_send_byte_fu_52_dummy_tmr_out_o;
    sc_signal< sc_logic > grp_bno055_uart_uart_send_byte_fu_52_dummy_tmr_out_o_ap_vld;
    sc_signal< sc_logic > grp_bno055_uart_wait_tmr_fu_64_ap_start;
    sc_signal< sc_logic > grp_bno055_uart_wait_tmr_fu_64_ap_done;
    sc_signal< sc_logic > grp_bno055_uart_wait_tmr_fu_64_ap_idle;
    sc_signal< sc_logic > grp_bno055_uart_wait_tmr_fu_64_ap_ready;
    sc_signal< sc_lv<1> > grp_bno055_uart_wait_tmr_fu_64_dummy_tmr_out_o;
    sc_signal< sc_logic > grp_bno055_uart_wait_tmr_fu_64_dummy_tmr_out_o_ap_vld;
    sc_signal< sc_logic > ap_reg_grp_bno055_uart_uart_receive_byte_fu_44_ap_start;
    sc_signal< sc_logic > ap_sig_cseq_ST_st13_fsm_12;
    sc_signal< bool > ap_sig_107;
    sc_signal< sc_logic > ap_sig_cseq_ST_st15_fsm_14;
    sc_signal< bool > ap_sig_114;
    sc_signal< sc_logic > ap_sig_cseq_ST_st14_fsm_13;
    sc_signal< bool > ap_sig_122;
    sc_signal< sc_logic > ap_sig_cseq_ST_st16_fsm_15;
    sc_signal< bool > ap_sig_129;
    sc_signal< sc_logic > ap_reg_grp_bno055_uart_uart_send_byte_fu_52_ap_start;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_146;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_155;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_163;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_172;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_180;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_187;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_195;
    sc_signal< sc_logic > ap_reg_grp_bno055_uart_wait_tmr_fu_64_ap_start;
    sc_signal< sc_logic > ap_sig_cseq_ST_st11_fsm_10;
    sc_signal< bool > ap_sig_228;
    sc_signal< sc_logic > ap_sig_cseq_ST_st12_fsm_11;
    sc_signal< bool > ap_sig_236;
    sc_signal< sc_lv<16> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<16> ap_ST_st1_fsm_0;
    static const sc_lv<16> ap_ST_st2_fsm_1;
    static const sc_lv<16> ap_ST_st3_fsm_2;
    static const sc_lv<16> ap_ST_st4_fsm_3;
    static const sc_lv<16> ap_ST_st5_fsm_4;
    static const sc_lv<16> ap_ST_st6_fsm_5;
    static const sc_lv<16> ap_ST_st7_fsm_6;
    static const sc_lv<16> ap_ST_st8_fsm_7;
    static const sc_lv<16> ap_ST_st9_fsm_8;
    static const sc_lv<16> ap_ST_st10_fsm_9;
    static const sc_lv<16> ap_ST_st11_fsm_10;
    static const sc_lv<16> ap_ST_st12_fsm_11;
    static const sc_lv<16> ap_ST_st13_fsm_12;
    static const sc_lv<16> ap_ST_st14_fsm_13;
    static const sc_lv<16> ap_ST_st15_fsm_14;
    static const sc_lv<16> ap_ST_st16_fsm_15;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<8> ap_const_lv8_AA;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<28> ap_const_lv28_1;
    static const sc_lv<32> ap_const_lv32_B;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_107();
    void thread_ap_sig_114();
    void thread_ap_sig_122();
    void thread_ap_sig_129();
    void thread_ap_sig_146();
    void thread_ap_sig_155();
    void thread_ap_sig_163();
    void thread_ap_sig_172();
    void thread_ap_sig_180();
    void thread_ap_sig_187();
    void thread_ap_sig_195();
    void thread_ap_sig_228();
    void thread_ap_sig_236();
    void thread_ap_sig_33();
    void thread_ap_sig_53();
    void thread_ap_sig_62();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st11_fsm_10();
    void thread_ap_sig_cseq_ST_st12_fsm_11();
    void thread_ap_sig_cseq_ST_st13_fsm_12();
    void thread_ap_sig_cseq_ST_st14_fsm_13();
    void thread_ap_sig_cseq_ST_st15_fsm_14();
    void thread_ap_sig_cseq_ST_st16_fsm_15();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_dummy_tmr_out_o();
    void thread_dummy_tmr_out_o_ap_vld();
    void thread_grp_bno055_uart_uart_receive_byte_fu_44_ap_start();
    void thread_grp_bno055_uart_uart_send_byte_fu_52_ap_start();
    void thread_grp_bno055_uart_uart_send_byte_fu_52_data();
    void thread_grp_bno055_uart_wait_tmr_fu_64_ap_start();
    void thread_reg_addr_cast_fu_72_p1();
    void thread_uart_tx();
    void thread_uart_tx_ap_vld();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
