// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bno055_uart_uart_send_byte (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data,
        uart_tx,
        uart_tx_ap_vld,
        dummy_tmr_out_i,
        dummy_tmr_out_o,
        dummy_tmr_out_o_ap_vld
);

parameter    ap_ST_st1_fsm_0 = 9'b1;
parameter    ap_ST_st2_fsm_1 = 9'b10;
parameter    ap_ST_st3_fsm_2 = 9'b100;
parameter    ap_ST_st4_fsm_3 = 9'b1000;
parameter    ap_ST_st5_fsm_4 = 9'b10000;
parameter    ap_ST_st6_fsm_5 = 9'b100000;
parameter    ap_ST_st7_fsm_6 = 9'b1000000;
parameter    ap_ST_st8_fsm_7 = 9'b10000000;
parameter    ap_ST_st9_fsm_8 = 9'b100000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv28_364 = 28'b1101100100;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_1 = 4'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] data;
output  [0:0] uart_tx;
output   uart_tx_ap_vld;
input  [0:0] dummy_tmr_out_i;
output  [0:0] dummy_tmr_out_o;
output   dummy_tmr_out_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] uart_tx;
reg uart_tx_ap_vld;
reg[0:0] dummy_tmr_out_o;
reg dummy_tmr_out_o_ap_vld;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_26;
wire   [3:0] i_1_fu_85_p2;
reg   [3:0] i_1_reg_118;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_49;
wire   [7:0] tmp_fu_106_p1;
reg   [7:0] tmp_reg_123;
wire   [0:0] exitcond_fu_79_p2;
wire    grp_bno055_uart_wait_tmr_fu_71_ap_start;
wire    grp_bno055_uart_wait_tmr_fu_71_ap_done;
wire    grp_bno055_uart_wait_tmr_fu_71_ap_idle;
wire    grp_bno055_uart_wait_tmr_fu_71_ap_ready;
wire   [0:0] grp_bno055_uart_wait_tmr_fu_71_dummy_tmr_out_o;
wire    grp_bno055_uart_wait_tmr_fu_71_dummy_tmr_out_o_ap_vld;
reg   [3:0] i_reg_51;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_75;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_85;
reg   [7:0] p_Val2_s_reg_62;
reg    ap_reg_grp_bno055_uart_wait_tmr_fu_71_ap_start;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_97;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_104;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_112;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_122;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_136;
wire   [0:0] dt_fu_91_p1;
wire   [6:0] data_assign_fu_96_p4;
reg   [8:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'b1;
#0 ap_reg_grp_bno055_uart_wait_tmr_fu_71_ap_start = 1'b0;
end

bno055_uart_wait_tmr grp_bno055_uart_wait_tmr_fu_71(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_bno055_uart_wait_tmr_fu_71_ap_start),
    .ap_done(grp_bno055_uart_wait_tmr_fu_71_ap_done),
    .ap_idle(grp_bno055_uart_wait_tmr_fu_71_ap_idle),
    .ap_ready(grp_bno055_uart_wait_tmr_fu_71_ap_ready),
    .tmr(ap_const_lv28_364),
    .dummy_tmr_out_i(dummy_tmr_out_i),
    .dummy_tmr_out_o(grp_bno055_uart_wait_tmr_fu_71_dummy_tmr_out_o),
    .dummy_tmr_out_o_ap_vld(grp_bno055_uart_wait_tmr_fu_71_dummy_tmr_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_bno055_uart_wait_tmr_fu_71_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) | (1'b1 == ap_sig_cseq_ST_st6_fsm_5) | (1'b1 == ap_sig_cseq_ST_st8_fsm_7))) begin
            ap_reg_grp_bno055_uart_wait_tmr_fu_71_ap_start <= 1'b1;
        end else if ((1'b1 == grp_bno055_uart_wait_tmr_fu_71_ap_ready)) begin
            ap_reg_grp_bno055_uart_wait_tmr_fu_71_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (~(1'b0 == grp_bno055_uart_wait_tmr_fu_71_ap_done)) begin
        if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
            i_reg_51 <= i_1_reg_118;
        end else if ((1'b1 == ap_sig_cseq_ST_st4_fsm_3)) begin
            i_reg_51 <= ap_const_lv4_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (~(1'b0 == grp_bno055_uart_wait_tmr_fu_71_ap_done)) begin
        if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
            p_Val2_s_reg_62 <= tmp_reg_123;
        end else if ((1'b1 == ap_sig_cseq_ST_st4_fsm_3)) begin
            p_Val2_s_reg_62 <= data;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        i_1_reg_118 <= i_1_fu_85_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & (exitcond_fu_79_p2 == 1'b0))) begin
        tmp_reg_123[6 : 0] <= tmp_fu_106_p1[6 : 0];
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | (~(1'b0 == grp_bno055_uart_wait_tmr_fu_71_ap_done) & (1'b1 == ap_sig_cseq_ST_st9_fsm_8)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~(1'b0 == grp_bno055_uart_wait_tmr_fu_71_ap_done) & (1'b1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_26) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_136) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_97) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_75) begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_49) begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_104) begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_85) begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_112) begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_122) begin
        ap_sig_cseq_ST_st9_fsm_8 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st4_fsm_3) & (1'b1 == grp_bno055_uart_wait_tmr_fu_71_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & (1'b1 == grp_bno055_uart_wait_tmr_fu_71_dummy_tmr_out_o_ap_vld)) | ((1'b1 == ap_sig_cseq_ST_st9_fsm_8) & (1'b1 == grp_bno055_uart_wait_tmr_fu_71_dummy_tmr_out_o_ap_vld)))) begin
        dummy_tmr_out_o = grp_bno055_uart_wait_tmr_fu_71_dummy_tmr_out_o;
    end else begin
        dummy_tmr_out_o = dummy_tmr_out_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st4_fsm_3) | (1'b1 == ap_sig_cseq_ST_st7_fsm_6) | (1'b1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        dummy_tmr_out_o_ap_vld = grp_bno055_uart_wait_tmr_fu_71_dummy_tmr_out_o_ap_vld;
    end else begin
        dummy_tmr_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & ~(exitcond_fu_79_p2 == 1'b0))) begin
        uart_tx = 1'b1;
    end else if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & (exitcond_fu_79_p2 == 1'b0))) begin
        uart_tx = dt_fu_91_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        uart_tx = 1'b0;
    end else begin
        uart_tx = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & (exitcond_fu_79_p2 == 1'b0)) | (1'b1 == ap_sig_cseq_ST_st2_fsm_1) | ((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & ~(exitcond_fu_79_p2 == 1'b0)))) begin
        uart_tx_ap_vld = 1'b1;
    end else begin
        uart_tx_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : begin
            if (~(1'b0 == grp_bno055_uart_wait_tmr_fu_71_ap_done)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st5_fsm_4 : begin
            if (~(exitcond_fu_79_p2 == 1'b0)) begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end
        end
        ap_ST_st6_fsm_5 : begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : begin
            if (~(1'b0 == grp_bno055_uart_wait_tmr_fu_71_ap_done)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st8_fsm_7 : begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : begin
            if (~(1'b0 == grp_bno055_uart_wait_tmr_fu_71_ap_done)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_sig_104 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_112 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_122 = (1'b1 == ap_CS_fsm[ap_const_lv32_8]);
end

always @ (*) begin
    ap_sig_136 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_26 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_49 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_75 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_85 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_97 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

assign data_assign_fu_96_p4 = {{p_Val2_s_reg_62[ap_const_lv32_7 : ap_const_lv32_1]}};

assign dt_fu_91_p1 = p_Val2_s_reg_62[0:0];

assign exitcond_fu_79_p2 = ((i_reg_51 == ap_const_lv4_8) ? 1'b1 : 1'b0);

assign grp_bno055_uart_wait_tmr_fu_71_ap_start = ap_reg_grp_bno055_uart_wait_tmr_fu_71_ap_start;

assign i_1_fu_85_p2 = (i_reg_51 + ap_const_lv4_1);

assign tmp_fu_106_p1 = data_assign_fu_96_p4;

always @ (posedge ap_clk) begin
    tmp_reg_123[7] <= 1'b0;
end

endmodule //bno055_uart_uart_send_byte
