#pragma line 1 "bno055_uart.c" ::: -10
#pragma line 1 "bno055_uart.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 147 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 283 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 54
#pragma line 421 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 181
#pragma line 7 "<command line>" 2 ::: 183
#pragma line 1 "<built-in>" 2 ::: 184
#pragma line 1 "bno055_uart.c" 2 ::: 185
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" 1 ::: 225
#pragma line 62 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" ::: 278
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 279
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 289
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 300
#pragma line 18 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 306
#pragma line 62 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 320
#pragma line 10 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 327
#pragma line 32 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 331
#pragma line 147 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 334
#pragma line 225 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 338
#pragma line 247 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 340
#pragma line 277 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 342
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 343
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 357
#pragma line 674 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 363
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 364
#pragma line 674 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 365
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 367
#pragma line 675 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 368
#pragma line 13 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 369
#pragma line 46 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 389
#pragma line 102 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 391
#pragma line 277 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 393
#pragma line 316 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 397
#pragma line 370 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 403
#pragma line 380 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 405
#pragma line 392 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 407
#pragma line 405 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 409
#pragma line 418 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 411
#pragma line 428 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 413
#pragma line 456 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 424
#pragma line 518 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 444
#pragma line 605 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 458
#pragma line 9 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 522
#pragma line 36 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 3 ::: 523
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 1 3 ::: 664
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 674
#pragma line 9 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 2 3 ::: 680
#pragma line 175 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 681
#pragma line 63 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" 2 ::: 682
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 683
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 693
#pragma line 9 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 699
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 702
#pragma line 11 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 710
#pragma line 26 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 714
#pragma line 84 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 726
#pragma line 120 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 745
#pragma line 157 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 747
#pragma line 312 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 893
#pragma line 330 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 901
#pragma line 373 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 937
#pragma line 417 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 972
#pragma line 475 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1002
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 1038
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 1048
#pragma line 9 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 1054
#pragma line 509 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1055
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 1058
#pragma line 511 "C:/Xilinx/Vivado_HLS/2016.1/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1066
#pragma line 64 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" 2 ::: 1067
#pragma line 77 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" ::: 1068
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 1069
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 1 ::: 1127
#pragma line 97 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" ::: 1181
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 1182
#pragma line 98 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 2221
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 2222
#pragma line 99 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 3249
#pragma line 108 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" ::: 3250
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.def" 1 ::: 3251
#pragma line 109 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 4290
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt_ext.def" 1 ::: 4291
#pragma line 110 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" 2 ::: 5318
#pragma line 131 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" ::: 5319
#pragma line 147 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_dt.h" ::: 5322
#pragma line 58 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5324
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" 1 ::: 5325
#pragma line 98 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5378
#pragma line 108 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5380
#pragma line 129 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5382
#pragma line 143 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5387
#pragma line 156 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5390
#pragma line 192 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5392
#pragma line 358 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\etc/autopilot_ssdm_bits.h" ::: 5394
#pragma line 59 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 5396
#pragma line 85 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" ::: 5397
#pragma line 114 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_apint.h" ::: 5399
#pragma line 78 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" 2 ::: 5401
#pragma line 88 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_cint.h" ::: 5402
#pragma line 39 "bno055_uart.c" 2 ::: 5404
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_utils.h" 1 ::: 5406
#pragma line 73 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_utils.h" ::: 5459
#pragma line 1 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 5460
#pragma line 74 "C:/Xilinx/Vivado_HLS/2016.1/common/technology/autopilot\\ap_utils.h" 2 ::: 5595
#pragma line 40 "bno055_uart.c" 2 ::: 5602
